Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Api\UserTag\UserTagUserController Class Reference
BristolSU\ControlDB\Http\Controllers\Api\UserTag\UserTagUserController Class Reference
Public Member Functions
index (UserTag $userTag)
update (UserTag $userTag, User $user)
destroy (UserTag $userTag, User $user)
Detailed Description
Definition at line 9 of file UserTagUserController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Api\UserTag\UserTagUserController::destroy (UserTag $userTag, User $user)
Definition at line 22 of file UserTagUserController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\removeUser().
index()
BristolSU\ControlDB\Http\Controllers\Api\UserTag\UserTagUserController::index (UserTag $userTag)
Definition at line 12 of file UserTagUserController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\users().
update()
BristolSU\ControlDB\Http\Controllers\Api\UserTag\UserTagUserController::update (UserTag $userTag, User $user)
Definition at line 17 of file UserTagUserController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\addUser().
The documentation for this class was generated from the following file:
src/Http/Controllers/Api/UserTag/UserTagUserController.php