Bristol SU Control: BristolSU\ControlDB\Models\Tags\PositionTagCategory Class Reference
BristolSU\ControlDB\Models\Tags\PositionTagCategory Class Reference
Public Member Functions
id ()
name ()
description ()
reference ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory
tags ()
Static Protected Member Functions
static boot ()
Protected Attributes
$table = 'control_tag_categories'
$fillable
Detailed Description
Position Tag Category
Definition at line 13 of file PositionTagCategory.php.
Member Function Documentation
boot()
static BristolSU\ControlDB\Models\Tags\PositionTagCategory::boot () static protected
Boot the model
Add a scope to only retrieve position tag categories
Definition at line 22 of file PositionTagCategory.php.
description()
BristolSU\ControlDB\Models\Tags\PositionTagCategory::description ()
Deacription of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory.
Definition at line 72 of file PositionTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\PositionTagCategory\setDescription().
id()
BristolSU\ControlDB\Models\Tags\PositionTagCategory::id ()
ID of the tag category
Returns
mixed
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory.
Definition at line 52 of file PositionTagCategory.php.
name()
BristolSU\ControlDB\Models\Tags\PositionTagCategory::name ()
Name of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory.
Definition at line 62 of file PositionTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\PositionTagCategory\setName().
reference()
BristolSU\ControlDB\Models\Tags\PositionTagCategory::reference ()
Reference of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory.
Definition at line 82 of file PositionTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\PositionTagCategory\setReference().
setDescription()
BristolSU\ControlDB\Models\Tags\PositionTagCategory::setDescription (string $description)
Set the description of the tag category
Parameters
string $description
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory.
Definition at line 103 of file PositionTagCategory.php.
References BristolSU\ControlDB\Models\Tags\PositionTagCategory\description().
setName()
BristolSU\ControlDB\Models\Tags\PositionTagCategory::setName (string $name)
Set the name of the tag category
Parameters
string $name
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory.
Definition at line 92 of file PositionTagCategory.php.
References BristolSU\ControlDB\Models\Tags\PositionTagCategory\name().
setReference()
BristolSU\ControlDB\Models\Tags\PositionTagCategory::setReference (string $reference)
Set the reference of the tag category
Parameters
string $reference
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory.
Definition at line 114 of file PositionTagCategory.php.
References BristolSU\ControlDB\Models\Tags\PositionTagCategory\reference().
Member Data Documentation
$fillable
BristolSU\ControlDB\Models\Tags\PositionTagCategory::$fillable protected
Initial value:
= [
        'name', 'description', 'reference'
    ]
Definition at line 43 of file PositionTagCategory.php.
$table
BristolSU\ControlDB\Models\Tags\PositionTagCategory::$table = 'control_tag_categories' protected
Definition at line 36 of file PositionTagCategory.php.
The documentation for this class was generated from the following file:
src/Models/Tags/PositionTagCategory.php