Bristol SU Control: BristolSU\ControlDB\Export\Formatter\Formatter Class Reference
BristolSU\ControlDB\Export\Formatter\Formatter Class Reference
Public Member Functions
__construct (array $config)
format ($items)
formatItem (FormattedItem $formattedItem)
handles ()
Public Attributes
const USERS = User::class
const GROUPS = Group::class
const ROLES = Role::class
const POSITIONS = Position::class
const USERTAGS = UserTag::class
const GROUPTAGS = GroupTag::class
const ROLETAGS = RoleTag::class
const POSITIONTAGS = PositionTag::class
const USERTAGCATEGORIES = UserTagCategory::class
const GROUPTAGCATEGORIES = GroupTagCategory::class
const ROLETAGCATEGORIES = RoleTagCategory::class
const POSITIONTAGCATEGORIES = PositionTagCategory::class
const ALL = 'all'
Protected Member Functions
config (string $key, $default=null)
canHandle (FormattedItem $item)
Protected Attributes
$config
Detailed Description
Definition at line 19 of file Formatter.php.
Constructor & Destructor Documentation
__construct()
BristolSU\ControlDB\Export\Formatter\Formatter::__construct (array $config)
Definition at line 52 of file Formatter.php.
References BristolSU\ControlDB\Export\Formatter\Formatter\$config, and BristolSU\ControlDB\Export\Formatter\Formatter\config().
Member Function Documentation
canHandle()
BristolSU\ControlDB\Export\Formatter\Formatter::canHandle (FormattedItem $item) protected
Definition at line 86 of file Formatter.php.
References BristolSU\ControlDB\Export\Formatter\Formatter\handles(), and BristolSU\ControlDB\Export\FormattedItem\isType().
Referenced by BristolSU\ControlDB\Export\Formatter\Formatter\format().
config()
BristolSU\ControlDB\Export\Formatter\Formatter::config (string $key, $default = null) protected
Parameters
string $key
null $default
Returns
mixed|null
Definition at line 63 of file Formatter.php.
Referenced by BristolSU\ControlDB\Export\Formatter\Formatter\__construct(), and BristolSU\ControlDB\Export\Formatter\Shared\SortByColumn\format().
format()
BristolSU\ControlDB\Export\Formatter\Formatter::format ($items)
Parameters
array|FormattedItem[] $items Items ready to format
Returns
array
Definition at line 75 of file Formatter.php.
References BristolSU\ControlDB\Export\Formatter\Formatter\canHandle(), BristolSU\ControlDB\Export\Formatter\Formatter\formatItem(), and BristolSU\ControlDB\Export\Formatter\Formatter\handles().
formatItem()
BristolSU\ControlDB\Export\Formatter\Formatter::formatItem (FormattedItem $formattedItem) abstract
Referenced by BristolSU\ControlDB\Export\Formatter\Formatter\format().
handles()
BristolSU\ControlDB\Export\Formatter\Formatter::handles () abstract
Referenced by BristolSU\ControlDB\Export\Formatter\Formatter\canHandle(), and BristolSU\ControlDB\Export\Formatter\Formatter\format().
Member Data Documentation
$config
BristolSU\ControlDB\Export\Formatter\Formatter::$config protected
Definition at line 50 of file Formatter.php.
Referenced by BristolSU\ControlDB\Export\Formatter\Formatter\__construct().
ALL
const BristolSU\ControlDB\Export\Formatter\Formatter::ALL = 'all'
Definition at line 46 of file Formatter.php.
GROUPS
const BristolSU\ControlDB\Export\Formatter\Formatter::GROUPS = Group::class
Definition at line 24 of file Formatter.php.
GROUPTAGCATEGORIES
const BristolSU\ControlDB\Export\Formatter\Formatter::GROUPTAGCATEGORIES = GroupTagCategory::class
Definition at line 40 of file Formatter.php.
GROUPTAGS
const BristolSU\ControlDB\Export\Formatter\Formatter::GROUPTAGS = GroupTag::class
Definition at line 32 of file Formatter.php.
POSITIONS
const BristolSU\ControlDB\Export\Formatter\Formatter::POSITIONS = Position::class
Definition at line 28 of file Formatter.php.
POSITIONTAGCATEGORIES
const BristolSU\ControlDB\Export\Formatter\Formatter::POSITIONTAGCATEGORIES = PositionTagCategory::class
Definition at line 44 of file Formatter.php.
POSITIONTAGS
const BristolSU\ControlDB\Export\Formatter\Formatter::POSITIONTAGS = PositionTag::class
Definition at line 36 of file Formatter.php.
ROLES
const BristolSU\ControlDB\Export\Formatter\Formatter::ROLES = Role::class
Definition at line 26 of file Formatter.php.
ROLETAGCATEGORIES
const BristolSU\ControlDB\Export\Formatter\Formatter::ROLETAGCATEGORIES = RoleTagCategory::class
Definition at line 42 of file Formatter.php.
ROLETAGS
const BristolSU\ControlDB\Export\Formatter\Formatter::ROLETAGS = RoleTag::class
Definition at line 34 of file Formatter.php.
USERS
const BristolSU\ControlDB\Export\Formatter\Formatter::USERS = User::class
Definition at line 22 of file Formatter.php.
USERTAGCATEGORIES
const BristolSU\ControlDB\Export\Formatter\Formatter::USERTAGCATEGORIES = UserTagCategory::class
Definition at line 38 of file Formatter.php.
USERTAGS
const BristolSU\ControlDB\Export\Formatter\Formatter::USERTAGS = UserTag::class
Definition at line 30 of file Formatter.php.
The documentation for this class was generated from the following file:
src/Export/Formatter/Formatter.php