Bristol SU Control: BristolSU\ControlDB\Http\Controllers\UserTagCategory\UserTagCategoryController Class Reference
BristolSU\ControlDB\Http\Controllers\UserTagCategory\UserTagCategoryController Class Reference
Public Member Functions
index (UserTagCategoryRepository $userTagCategoryRepository)
show (UserTagCategory $userTagCategory)
store (UserTagCategoryStoreRequest $request, UserTagCategoryRepository $userTagCategoryRepository)
update (UserTagCategory $userTagCategory, UserTagCategoryUpdateRequest $request)
destroy (UserTagCategory $userTagCategory, UserTagCategoryRepository $userTagCategoryRepository)
Public Member Functions inherited from BristolSU\ControlDB\Http\Controllers\Controller
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Handle user tag categories
Definition at line 14 of file UserTagCategoryController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\UserTagCategory\UserTagCategoryController::destroy (UserTagCategory $userTagCategory, UserTagCategoryRepository $userTagCategoryRepository)
Delete a tag category
Parameters
UserTagCategory $userTagCategory
UserTagCategoryRepository $userTagCategoryRepository
Definition at line 81 of file UserTagCategoryController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory\id().
index()
BristolSU\ControlDB\Http\Controllers\UserTagCategory\UserTagCategoryController::index (UserTagCategoryRepository $userTagCategoryRepository)
Get all user tag categories
Parameters
UserTagCategoryRepository $userTagCategoryRepository
Returns
Definition at line 21 of file UserTagCategoryController.php.
References BristolSU\ControlDB\Http\Controllers\Controller\paginate().
show()
BristolSU\ControlDB\Http\Controllers\UserTagCategory\UserTagCategoryController::show (UserTagCategory $userTagCategory)
Get information about a single tag category
Parameters
UserTagCategory $userTagCategory
Returns
UserTagCategory
Definition at line 32 of file UserTagCategoryController.php.
store()
BristolSU\ControlDB\Http\Controllers\UserTagCategory\UserTagCategoryController::store (UserTagCategoryStoreRequest $request, UserTagCategoryRepository $userTagCategoryRepository)
Create a new tag category
Parameters
UserTagCategoryStoreRequest $request
UserTagCategoryRepository $userTagCategoryRepository
Returns
UserTagCategory
Definition at line 44 of file UserTagCategoryController.php.
update()
BristolSU\ControlDB\Http\Controllers\UserTagCategory\UserTagCategoryController::update (UserTagCategory $userTagCategory, UserTagCategoryUpdateRequest $request)
Update a tag category
Parameters
UserTagCategory $userTagCategory
UserTagCategoryUpdateRequest $request
Returns
UserTagCategory
Definition at line 60 of file UserTagCategoryController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory\setDescription(), BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory\setName(), and BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory\setReference().
The documentation for this class was generated from the following file:
src/Http/Controllers/UserTagCategory/UserTagCategoryController.php