Bristol SU Control: BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag Class Reference
BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag Class Reference
Public Member Functions
addTagToPosition (PositionTag $positionTag, Position $position)
removeTagFromPosition (PositionTag $positionTag, Position $position)
getTagsThroughPosition (Position $position)
getPositionsThroughTag (PositionTag $positionTag)
Detailed Description
Handles the tagging of positions
Definition at line 13 of file PositionPositionTag.php.
Member Function Documentation
addTagToPosition()
BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag::addTagToPosition (PositionTag $positionTag, Position $position)
Tag a position
Parameters
PositionTag $positionTag Tag to tag the position with
Position $position Position to tag
Returns
void
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\PositionPositionTag.
Definition at line 23 of file PositionPositionTag.php.
References BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\id(), and BristolSU\ControlDB\Contracts\Models\Position\id().
getPositionsThroughTag()
BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag::getPositionsThroughTag (PositionTag $positionTag)
Get all positions tagged with a tag
Parameters
PositionTag $positionTag Tag to use to retrieve positions
Returns
Collection|Position[] Positions tagged with the given tag
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\PositionPositionTag.
Definition at line 69 of file PositionPositionTag.php.
References BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\id(), and BristolSU\ControlDB\Contracts\Models\Position\id().
getTagsThroughPosition()
BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag::getTagsThroughPosition (Position $position)
Get all tags a position is tagged with
Parameters
Position $position Position to retrieve tags from
Returns
Collection|PositionTag[] Tags the position is tagged with
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\PositionPositionTag.
Definition at line 51 of file PositionPositionTag.php.
References BristolSU\ControlDB\Contracts\Models\Position\id(), and BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\id().
removeTagFromPosition()
BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag::removeTagFromPosition (PositionTag $positionTag, Position $position)
Remove a tag from a position
Parameters
PositionTag $positionTag Tag to remove from the position
Position $position Position to remove the tag from
Returns
void
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\PositionPositionTag.
Definition at line 38 of file PositionPositionTag.php.
References BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\id(), and BristolSU\ControlDB\Contracts\Models\Position\id().
The documentation for this class was generated from the following file:
src/Repositories/Pivots/Tags/PositionPositionTag.php