Bristol SU Control: BristolSU\ControlDB\Http\Controllers\UserTag\UserTagUserController Class Reference
BristolSU\ControlDB\Http\Controllers\UserTag\UserTagUserController Class Reference
Public Member Functions
index (UserTag $userTag)
update (UserTag $userTag, User $user)
destroy (UserTag $userTag, User $user)
Detailed Description
Handle the link between a user tag and a user
Definition at line 12 of file UserTagUserController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\UserTag\UserTagUserController::destroy (UserTag $userTag, User $user)
Remove the user from the tag
Parameters
UserTag $userTag
User $user
Definition at line 42 of file UserTagUserController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\removeUser().
index()
BristolSU\ControlDB\Http\Controllers\UserTag\UserTagUserController::index (UserTag $userTag)
Get all users with the given tag
Parameters
UserTag $userTag
Returns
Definition at line 20 of file UserTagUserController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\users().
update()
BristolSU\ControlDB\Http\Controllers\UserTag\UserTagUserController::update (UserTag $userTag, User $user)
Add the user to the tag
Parameters
UserTag $userTag
User $user
Definition at line 31 of file UserTagUserController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\addUser().
The documentation for this class was generated from the following file:
src/Http/Controllers/UserTag/UserTagUserController.php