Bristol SU Control: BristolSU\ControlDB\AdditionalProperties\AdditionalPropertySingletonStore Class Reference
BristolSU\ControlDB\AdditionalProperties\AdditionalPropertySingletonStore Class Reference
Public Member Functions
addProperty (string $model, string $key)
hasProperties (string $model)
getProperties (string $model)
Private Attributes
$properties = []
Detailed Description
Handles storing the additional properties models can define using a local array
Definition at line 8 of file AdditionalPropertySingletonStore.php.
Member Function Documentation
addProperty()
BristolSU\ControlDB\AdditionalProperties\AdditionalPropertySingletonStore::addProperty (string $model, string $key)
Add a property to a model.
Properties must be initialised before they can be used.
Parameters
string $model Model class name to add the property to
string $key Key of the property
Returns
void
Implements BristolSU\ControlDB\AdditionalProperties\AdditionalPropertyStore.
Definition at line 29 of file AdditionalPropertySingletonStore.php.
References BristolSU\ControlDB\AdditionalProperties\AdditionalPropertySingletonStore\hasProperties().
getProperties()
BristolSU\ControlDB\AdditionalProperties\AdditionalPropertySingletonStore::getProperties (string $model)
Get all properties a model has
Parameters
string $model Full class name of the model
Returns
array Array of property keys.
Implements BristolSU\ControlDB\AdditionalProperties\AdditionalPropertyStore.
Definition at line 53 of file AdditionalPropertySingletonStore.php.
References BristolSU\ControlDB\AdditionalProperties\AdditionalPropertySingletonStore\hasProperties().
hasProperties()
BristolSU\ControlDB\AdditionalProperties\AdditionalPropertySingletonStore::hasProperties (string $model)
Does the given model have any properties
Parameters
string $model Full class name of the model
Returns
bool If the model has properties
Implements BristolSU\ControlDB\AdditionalProperties\AdditionalPropertyStore.
Definition at line 42 of file AdditionalPropertySingletonStore.php.
Referenced by BristolSU\ControlDB\AdditionalProperties\AdditionalPropertySingletonStore\addProperty(), and BristolSU\ControlDB\AdditionalProperties\AdditionalPropertySingletonStore\getProperties().
Member Data Documentation
$properties
BristolSU\ControlDB\AdditionalProperties\AdditionalPropertySingletonStore::$properties = [] private
Definition at line 18 of file AdditionalPropertySingletonStore.php.
The documentation for this class was generated from the following file:
src/AdditionalProperties/AdditionalPropertySingletonStore.php