Bristol SU Control: BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties Class Reference
BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties Class Reference
Public Member Functions
initializeHasAdditionalProperties ()
getAdditionalAttribute (string $key)
setAdditionalAttribute (string $key, $value)
saveAdditionalAttribute (string $key, $value)
getAttribute ($key)
setAttribute ($key, $value)
getAdditionalAttributesAttribute ()
__call ($method, $args)
Static Public Member Functions
static addProperty (string $key)
static getAdditionalAttributes ()
Private Member Functions
getColumnName ()
Detailed Description
Allow a model to have any arbitrary properties, set at runtime
Definition at line 12 of file HasAdditionalProperties.php.
Member Function Documentation
__call()
BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::__call ($method, $args)
Dynamically define accessors for the appended properties.
By catching all method calls, we can check if they are calls for an accessor or mutator to an attribute and carry out the corresponding action.
Parameters
string $method Method of the call
array $args Arguments for the call
Returns
mixed
Definition at line 158 of file HasAdditionalProperties.php.
References BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\getAdditionalAttribute(), and BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\setAdditionalAttribute().
addProperty()
static BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::addProperty (string $key) static
Add an additional property
Parameters
$key
Definition at line 38 of file HasAdditionalProperties.php.
getAdditionalAttribute()
BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::getAdditionalAttribute (string $key)
Retrieve an additional attribute value
Parameters
string $key Key of the attribute
Returns
mixed Value of the attribute
Definition at line 59 of file HasAdditionalProperties.php.
References BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\getColumnName().
Referenced by BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\__call(), and BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\getAttribute().
getAdditionalAttributes()
static BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::getAdditionalAttributes () static
Get all additional attributes the model is using
Returns
array
Definition at line 48 of file HasAdditionalProperties.php.
getAdditionalAttributesAttribute()
BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::getAdditionalAttributesAttribute ()
Cast the additional attributes column to an array, or return an empty array by default.
Returns
array|mixed
Definition at line 127 of file HasAdditionalProperties.php.
References BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\getColumnName().
getAttribute()
BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::getAttribute ($key)
Override the default getAttribute function
Any time an attribute is retrieved, we will check if it's an additional property and return it if so
Parameters
string $key Key of the property to retrieve
Returns
mixed Value of the property
Definition at line 96 of file HasAdditionalProperties.php.
References BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\getAdditionalAttribute().
getColumnName()
BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::getColumnName () private
Get the name of the additional attributes column
Returns
string Name of the additional attributes column
Definition at line 143 of file HasAdditionalProperties.php.
Referenced by BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\getAdditionalAttribute(), BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\getAdditionalAttributesAttribute(), BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\initializeHasAdditionalProperties(), and BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\setAdditionalAttribute().
initializeHasAdditionalProperties()
BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::initializeHasAdditionalProperties ()
Initialise the trait
Add all additional properties to the appends array
Add additional_properties column to hidden
Cast the additional_properties column to an array
Definition at line 22 of file HasAdditionalProperties.php.
References BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\getColumnName().
saveAdditionalAttribute()
BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::saveAdditionalAttribute (string $key, $value)
Save an additional attribute value
Parameters
string $key Key of the attribute
mixed $value Value of the attribute
Definition at line 82 of file HasAdditionalProperties.php.
References BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\setAdditionalAttribute().
setAdditionalAttribute()
BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::setAdditionalAttribute (string $key, $value)
Set an additional attribute value
Parameters
string $key Key of the attribute
mixed $value Value of the attribute
Definition at line 71 of file HasAdditionalProperties.php.
References BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\getColumnName().
Referenced by BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\__call(), BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\saveAdditionalAttribute(), and BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\setAttribute().
setAttribute()
BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties::setAttribute ($key, $value)
Override the default getAttribute function
Any time an attribute is set, we will check if it's an additional property and set it correspondingly if so
Parameters
string $key Key of the property to retrieve
mixed $value Value of the attribute
Returns
mixed Value of the property
Definition at line 113 of file HasAdditionalProperties.php.
References BristolSU\ControlDB\AdditionalProperties\HasAdditionalProperties\setAdditionalAttribute().
The documentation for this class was generated from the following file:
src/AdditionalProperties/HasAdditionalProperties.php