Bristol SU Control: BristolSU\ControlDB\Traits\Tags\PositionTagTrait Class Reference
BristolSU\ControlDB\Traits\Tags\PositionTagTrait Class Reference
Public Member Functions
fullReference ()
category ()
positions ()
addPosition (Position $position)
removePosition (Position $position)
Detailed Description
Definition at line 10 of file PositionTagTrait.php.
Member Function Documentation
addPosition()
BristolSU\ControlDB\Traits\Tags\PositionTagTrait::addPosition (Position $position)
Definition at line 44 of file PositionTagTrait.php.
category()
BristolSU\ControlDB\Traits\Tags\PositionTagTrait::category ()
Tag Category
Returns
PositionTagCategory
Definition at line 29 of file PositionTagTrait.php.
References BristolSU\ControlDB\Contracts\Repositories\Tags\PositionTagCategory\getById().
Referenced by BristolSU\ControlDB\Traits\Tags\PositionTagTrait\fullReference().
fullReference()
BristolSU\ControlDB\Traits\Tags\PositionTagTrait::fullReference ()
Full reference of the tag
This should be the tag category reference and the tag reference, separated with a period.
Returns
string
Definition at line 19 of file PositionTagTrait.php.
References BristolSU\ControlDB\Traits\Tags\PositionTagTrait\category().
positions()
BristolSU\ControlDB\Traits\Tags\PositionTagTrait::positions ()
Positions who have this tag
Returns
Collection
Definition at line 39 of file PositionTagTrait.php.
removePosition()
BristolSU\ControlDB\Traits\Tags\PositionTagTrait::removePosition (Position $position)
Definition at line 49 of file PositionTagTrait.php.
The documentation for this class was generated from the following file:
src/Traits/Tags/PositionTagTrait.php