Bristol SU Control: BristolSU\ControlDB\Http\Controllers\User\UserController Class Reference
BristolSU\ControlDB\Http\Controllers\User\UserController Class Reference
Public Member Functions
index (Request $request, UserRepository $userRepository)
search (Request $request, UserRepository $userRepository, DataUserRepository $dataUserRepository)
show (User $user)
store (StoreUserRequest $request, UserRepository $userRepository, DataUserRepository $dataUserRepository)
update (User $user, StoreUserRequest $request, UserRepository $userRepository, DataUserRepository $dataUserRepository)
destroy (User $user, UserRepository $userRepository)
Public Member Functions inherited from BristolSU\ControlDB\Http\Controllers\Controller
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Handle the user model
Definition at line 19 of file UserController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\User\UserController::destroy (User $user, UserRepository $userRepository)
Delete a user
Parameters
User $user
UserRepository $userRepository
Definition at line 146 of file UserController.php.
References BristolSU\ControlDB\Contracts\Models\User\id().
index()
BristolSU\ControlDB\Http\Controllers\User\UserController::index (Request $request, UserRepository $userRepository)
Get all users
Parameters
Request $request
UserRepository $userRepository
Returns
LengthAwarePaginator
Definition at line 29 of file UserController.php.
References BristolSU\ControlDB\Http\Controllers\Controller\paginationResponse().
search()
BristolSU\ControlDB\Http\Controllers\User\UserController::search (Request $request, UserRepository $userRepository, DataUserRepository $dataUserRepository)
Definition at line 40 of file UserController.php.
References BristolSU\ControlDB\Http\Controllers\Controller\paginate().
show()
BristolSU\ControlDB\Http\Controllers\User\UserController::show (User $user)
Get information about a specific user
Parameters
User $user
Returns
User
Definition at line 70 of file UserController.php.
store()
BristolSU\ControlDB\Http\Controllers\User\UserController::store (StoreUserRequest $request, UserRepository $userRepository, DataUserRepository $dataUserRepository)
Create a new user
Parameters
StoreUserRequest $request
UserRepository $userRepository
DataUserRepository $dataUserRepository
Returns
User
Definition at line 83 of file UserController.php.
update()
BristolSU\ControlDB\Http\Controllers\User\UserController::update (User $user, StoreUserRequest $request, UserRepository $userRepository, DataUserRepository $dataUserRepository)
Update a user
Parameters
User $user
StoreUserRequest $request
UserRepository $userRepository
DataUserRepository $dataUserRepository
Returns
User
Definition at line 111 of file UserController.php.
References BristolSU\ControlDB\Contracts\Models\User\data().
The documentation for this class was generated from the following file:
src/Http/Controllers/User/UserController.php