Bristol SU Control: BristolSU\ControlDB\Http\Controllers\User\UserGroupController Class Reference
BristolSU\ControlDB\Http\Controllers\User\UserGroupController Class Reference
Public Member Functions
index (User $user)
update (User $user, Group $group)
destroy (User $user, Group $group)
Public Member Functions inherited from BristolSU\ControlDB\Http\Controllers\Controller
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Handles the linking of users and groups
Definition at line 14 of file UserGroupController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\User\UserGroupController::destroy (User $user, Group $group)
Remove a group from a user
Parameters
User $user
Group $group
Definition at line 45 of file UserGroupController.php.
References BristolSU\ControlDB\Contracts\Models\User\removeGroup().
index()
BristolSU\ControlDB\Http\Controllers\User\UserGroupController::index (User $user)
Get all groups that belong to a user
Parameters
User $user
Returns
Definition at line 23 of file UserGroupController.php.
References BristolSU\ControlDB\Contracts\Models\User\groups(), and BristolSU\ControlDB\Http\Controllers\Controller\paginate().
update()
BristolSU\ControlDB\Http\Controllers\User\UserGroupController::update (User $user, Group $group)
Add a group to a user
Parameters
User $user
Group $group
Definition at line 34 of file UserGroupController.php.
References BristolSU\ControlDB\Contracts\Models\User\addGroup().
The documentation for this class was generated from the following file:
src/Http/Controllers/User/UserGroupController.php