Bristol SU Control: BristolSU\ControlDB\Export\Handler\Handler Class Reference
BristolSU\ControlDB\Export\Handler\Handler Class Reference
Public Member Functions
__construct (array $config)
export ($items=[])
Protected Member Functions
prepareItems ($items)
getFormatters ()
save (array $items)
config (string $key, $default=null)
Private Member Functions
logTime (string $formatter, float $time)
Private Attributes
$config
Detailed Description
Definition at line 10 of file Handler.php.
Constructor & Destructor Documentation
__construct()
BristolSU\ControlDB\Export\Handler\Handler::__construct (array $config)
Definition at line 17 of file Handler.php.
References BristolSU\ControlDB\Export\Handler\Handler\$config, and BristolSU\ControlDB\Export\Handler\Handler\config().
Member Function Documentation
config()
BristolSU\ControlDB\Export\Handler\Handler::config (string $key, $default = null) protected
Parameters
string $key
null $default
Returns
mixed|null
Definition at line 77 of file Handler.php.
Referenced by BristolSU\ControlDB\Export\Handler\Handler\__construct(), BristolSU\ControlDB\Export\Handler\Handler\getFormatters(), BristolSU\ControlDB\Export\Handler\Handler\logTime(), and BristolSU\ControlDB\Export\Handler\SaveCsvHandler\save().
export()
BristolSU\ControlDB\Export\Handler\Handler::export ($items = [])
Definition at line 37 of file Handler.php.
References BristolSU\ControlDB\Export\Handler\Handler\getFormatters(), BristolSU\ControlDB\Export\Handler\Handler\logTime(), BristolSU\ControlDB\Export\Handler\Handler\prepareItems(), and BristolSU\ControlDB\Export\Handler\Handler\save().
getFormatters()
BristolSU\ControlDB\Export\Handler\Handler::getFormatters () protected
Returns
Formatter[]
Definition at line 55 of file Handler.php.
References BristolSU\ControlDB\Export\Handler\Handler\config(), and BristolSU\ControlDB\Export\Handler\Handler\save().
Referenced by BristolSU\ControlDB\Export\Handler\Handler\export().
logTime()
BristolSU\ControlDB\Export\Handler\Handler::logTime (string $formatter, float $time) private
Definition at line 85 of file Handler.php.
References BristolSU\ControlDB\Export\Handler\Handler\config().
Referenced by BristolSU\ControlDB\Export\Handler\Handler\export().
prepareItems()
BristolSU\ControlDB\Export\Handler\Handler::prepareItems ($items) protected
Prepare items by transforming them to formattable items
Parameters
$items
Returns
FormattedItem[]
Definition at line 28 of file Handler.php.
References BristolSU\ControlDB\Export\FormattedItem\create().
Referenced by BristolSU\ControlDB\Export\Handler\Handler\export().
save()
BristolSU\ControlDB\Export\Handler\Handler::save (array $items) abstract protected
Parameters
FormattedItem[] $items
Returns
mixed
Referenced by BristolSU\ControlDB\Export\Handler\Handler\export(), and BristolSU\ControlDB\Export\Handler\Handler\getFormatters().
Member Data Documentation
$config
BristolSU\ControlDB\Export\Handler\Handler::$config private
Definition at line 15 of file Handler.php.
Referenced by BristolSU\ControlDB\Export\Handler\Handler\__construct().
The documentation for this class was generated from the following file:
src/Export/Handler/Handler.php