Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Controller Class Reference
BristolSU\ControlDB\Http\Controllers\Controller Class Reference
Public Member Functions
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Definition at line 11 of file Controller.php.
Member Function Documentation
paginate()
BristolSU\ControlDB\Http\Controllers\Controller::paginate ($items)
Definition at line 14 of file Controller.php.
References BristolSU\ControlDB\Http\Controllers\Controller\paginationResponse().
Referenced by BristolSU\ControlDB\Http\Controllers\Group\GroupRoleController\index(), BristolSU\ControlDB\Http\Controllers\GroupTagCategory\GroupTagCategoryGroupTagController\index(), BristolSU\ControlDB\Http\Controllers\RoleTag\RoleTagRoleController\index(), BristolSU\ControlDB\Http\Controllers\Position\PositionRoleController\index(), BristolSU\ControlDB\Http\Controllers\RoleTagCategory\RoleTagCategoryRoleTagController\index(), BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagGroupController\index(), BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagPositionController\index(), BristolSU\ControlDB\Http\Controllers\UserTag\UserTagUserController\index(), BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryPositionTagController\index(), BristolSU\ControlDB\Http\Controllers\UserTagCategory\UserTagCategoryUserTagController\index(), BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController\index(), BristolSU\ControlDB\Http\Controllers\Role\RoleRoleTagController\index(), BristolSU\ControlDB\Http\Controllers\Group\GroupUserController\index(), BristolSU\ControlDB\Http\Controllers\UserTagCategory\UserTagCategoryController\index(), BristolSU\ControlDB\Http\Controllers\RoleTagCategory\RoleTagCategoryController\index(), BristolSU\ControlDB\Http\Controllers\Position\PositionPositionTagController\index(), BristolSU\ControlDB\Http\Controllers\User\UserUserTagController\index(), BristolSU\ControlDB\Http\Controllers\GroupTagCategory\GroupTagCategoryController\index(), BristolSU\ControlDB\Http\Controllers\User\UserRoleController\index(), BristolSU\ControlDB\Http\Controllers\RoleTag\RoleTagController\index(), BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController\index(), BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController\index(), BristolSU\ControlDB\Http\Controllers\Role\RoleUserController\index(), BristolSU\ControlDB\Http\Controllers\User\UserGroupController\index(), BristolSU\ControlDB\Http\Controllers\Group\GroupGroupTagController\index(), BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagController\index(), BristolSU\ControlDB\Http\Controllers\Group\GroupController\search(), BristolSU\ControlDB\Http\Controllers\Position\PositionController\search(), and BristolSU\ControlDB\Http\Controllers\User\UserController\search().
paginationResponse()
BristolSU\ControlDB\Http\Controllers\Controller::paginationResponse ($items, $count)
Definition at line 24 of file Controller.php.
Referenced by BristolSU\ControlDB\Http\Controllers\Group\GroupController\index(), BristolSU\ControlDB\Http\Controllers\Role\RoleController\index(), BristolSU\ControlDB\Http\Controllers\Position\PositionController\index(), BristolSU\ControlDB\Http\Controllers\User\UserController\index(), and BristolSU\ControlDB\Http\Controllers\Controller\paginate().
The documentation for this class was generated from the following file:
src/Http/Controllers/Controller.php