Bristol SU Control: BristolSU\ControlDB\Models\Tags\UserTagCategory Class Reference
BristolSU\ControlDB\Models\Tags\UserTagCategory Class Reference
Public Member Functions
id ()
name ()
description ()
reference ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory
tags ()
Static Protected Member Functions
static boot ()
Protected Attributes
$table = 'control_tag_categories'
$fillable
Detailed Description
User Tag Category
Definition at line 13 of file UserTagCategory.php.
Member Function Documentation
boot()
static BristolSU\ControlDB\Models\Tags\UserTagCategory::boot () static protected
Boot the model
Add a scope to only retrieve user tag categories
Definition at line 22 of file UserTagCategory.php.
description()
BristolSU\ControlDB\Models\Tags\UserTagCategory::description ()
Deacription of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory.
Definition at line 72 of file UserTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\UserTagCategory\setDescription().
id()
BristolSU\ControlDB\Models\Tags\UserTagCategory::id ()
ID of the tag category
Returns
mixed
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory.
Definition at line 52 of file UserTagCategory.php.
name()
BristolSU\ControlDB\Models\Tags\UserTagCategory::name ()
Name of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory.
Definition at line 62 of file UserTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\UserTagCategory\setName().
reference()
BristolSU\ControlDB\Models\Tags\UserTagCategory::reference ()
Reference of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory.
Definition at line 82 of file UserTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\UserTagCategory\setReference().
setDescription()
BristolSU\ControlDB\Models\Tags\UserTagCategory::setDescription (string $description)
Set the description of the tag category
Parameters
string $description
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory.
Definition at line 103 of file UserTagCategory.php.
References BristolSU\ControlDB\Models\Tags\UserTagCategory\description().
setName()
BristolSU\ControlDB\Models\Tags\UserTagCategory::setName (string $name)
Set the name of the tag category
Parameters
string $name
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory.
Definition at line 92 of file UserTagCategory.php.
References BristolSU\ControlDB\Models\Tags\UserTagCategory\name().
setReference()
BristolSU\ControlDB\Models\Tags\UserTagCategory::setReference (string $reference)
Set the reference of the tag category
Parameters
string $reference
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory.
Definition at line 114 of file UserTagCategory.php.
References BristolSU\ControlDB\Models\Tags\UserTagCategory\reference().
Member Data Documentation
$fillable
BristolSU\ControlDB\Models\Tags\UserTagCategory::$fillable protected
Initial value:
= [
        'name', 'description', 'reference'
    ]
Definition at line 43 of file UserTagCategory.php.
$table
BristolSU\ControlDB\Models\Tags\UserTagCategory::$table = 'control_tag_categories' protected
Definition at line 36 of file UserTagCategory.php.
The documentation for this class was generated from the following file:
src/Models/Tags/UserTagCategory.php