Bristol SU Control: BristolSU\ControlDB\Http\Controllers\RoleTag\RoleTagController Class Reference
BristolSU\ControlDB\Http\Controllers\RoleTag\RoleTagController Class Reference
Public Member Functions
index (RoleTagRepository $roleTagRepository)
show (RoleTag $roleTag)
store (RoleTagStoreRequest $request, RoleTagRepository $roleTagRepository)
update (RoleTag $roleTag, RoleTagUpdateRequest $request)
destroy (RoleTag $roleTag, RoleTagRepository $roleTagRepository)
Detailed Description
Handle role tags
Definition at line 14 of file RoleTagController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\RoleTag\RoleTagController::destroy (RoleTag $roleTag, RoleTagRepository $roleTagRepository)
Delete a role tag
Parameters
RoleTag $roleTag
RoleTagRepository $roleTagRepository
Definition at line 87 of file RoleTagController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\RoleTag\id().
index()
BristolSU\ControlDB\Http\Controllers\RoleTag\RoleTagController::index (RoleTagRepository $roleTagRepository)
Get all role tags
Parameters
RoleTagRepository $roleTagRepository
Returns
RoleTag[]|
Definition at line 23 of file RoleTagController.php.
show()
BristolSU\ControlDB\Http\Controllers\RoleTag\RoleTagController::show (RoleTag $roleTag)
Show information about a single role tag
Parameters
RoleTag $roleTag
Returns
RoleTag
Definition at line 34 of file RoleTagController.php.
store()
BristolSU\ControlDB\Http\Controllers\RoleTag\RoleTagController::store (RoleTagStoreRequest $request, RoleTagRepository $roleTagRepository)
Create a new role tag
Parameters
RoleTagStoreRequest $request
RoleTagRepository $roleTagRepository
Returns
RoleTag
Definition at line 46 of file RoleTagController.php.
update()
BristolSU\ControlDB\Http\Controllers\RoleTag\RoleTagController::update (RoleTag $roleTag, RoleTagUpdateRequest $request)
Update a role tag
Parameters
RoleTag $roleTag
RoleTagUpdateRequest $request
Returns
RoleTag
Definition at line 63 of file RoleTagController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\RoleTag\setDescription(), BristolSU\ControlDB\Contracts\Models\Tags\RoleTag\setName(), BristolSU\ControlDB\Contracts\Models\Tags\RoleTag\setReference(), and BristolSU\ControlDB\Contracts\Models\Tags\RoleTag\setTagCategoryId().
The documentation for this class was generated from the following file:
src/Http/Controllers/RoleTag/RoleTagController.php