Bristol SU Control: BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController Class Reference
BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController Class Reference
Public Member Functions
index (PositionTagCategoryRepository $positionTagCategoryRepository)
show (PositionTagCategory $positionTagCategory)
store (PositionTagCategoryStoreRequest $request, PositionTagCategoryRepository $positionTagCategoryRepository)
update (PositionTagCategory $positionTagCategory, PositionTagCategoryUpdateRequest $request)
destroy (PositionTagCategory $positionTagCategory, PositionTagCategoryRepository $positionTagCategoryRepository)
Detailed Description
Handle position tag categories
Definition at line 14 of file PositionTagCategoryController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController::destroy (PositionTagCategory $positionTagCategory, PositionTagCategoryRepository $positionTagCategoryRepository)
Delete a tag category
Parameters
PositionTagCategory $positionTagCategory
PositionTagCategoryRepository $positionTagCategoryRepository
Definition at line 81 of file PositionTagCategoryController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory\id().
index()
BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController::index (PositionTagCategoryRepository $positionTagCategoryRepository)
Get all position tag categories
Parameters
PositionTagCategoryRepository $positionTagCategoryRepository
Returns
PositionTagCategory[]|
Definition at line 21 of file PositionTagCategoryController.php.
show()
BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController::show (PositionTagCategory $positionTagCategory)
Get information about a single tag category
Parameters
PositionTagCategory $positionTagCategory
Returns
PositionTagCategory
Definition at line 32 of file PositionTagCategoryController.php.
store()
BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController::store (PositionTagCategoryStoreRequest $request, PositionTagCategoryRepository $positionTagCategoryRepository)
Create a new tag category
Parameters
PositionTagCategoryStoreRequest $request
PositionTagCategoryRepository $positionTagCategoryRepository
Returns
PositionTagCategory
Definition at line 44 of file PositionTagCategoryController.php.
update()
BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController::update (PositionTagCategory $positionTagCategory, PositionTagCategoryUpdateRequest $request)
Update a tag category
Parameters
PositionTagCategory $positionTagCategory
PositionTagCategoryUpdateRequest $request
Returns
PositionTagCategory
Definition at line 60 of file PositionTagCategoryController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory\setDescription(), BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory\setName(), and BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory\setReference().
The documentation for this class was generated from the following file:
src/Http/Controllers/PositionTagCategory/PositionTagCategoryController.php