Bristol SU Control: BristolSU\ControlDB\Http\Controllers\User\UserRoleController Class Reference
BristolSU\ControlDB\Http\Controllers\User\UserRoleController Class Reference
Public Member Functions
index (User $user)
update (User $user, Role $role)
destroy (User $user, Role $role)
Detailed Description
Handles the linking of users and roles
Definition at line 14 of file UserRoleController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\User\UserRoleController::destroy (User $user, Role $role)
Remove a role from a user
Parameters
User $user
Role $role
Definition at line 45 of file UserRoleController.php.
References BristolSU\ControlDB\Contracts\Models\User\removeRole().
index()
BristolSU\ControlDB\Http\Controllers\User\UserRoleController::index (User $user)
Get all roles that belong to a user
Parameters
User $user
Returns
Definition at line 23 of file UserRoleController.php.
References BristolSU\ControlDB\Contracts\Models\User\roles().
update()
BristolSU\ControlDB\Http\Controllers\User\UserRoleController::update (User $user, Role $role)
Add a role to a user
Parameters
User $user
Role $role
Definition at line 34 of file UserRoleController.php.
References BristolSU\ControlDB\Contracts\Models\User\addRole().
The documentation for this class was generated from the following file:
src/Http/Controllers/User/UserRoleController.php