Bristol SU Control: BristolSU\ControlDB\Models\Tags\UserTag Class Reference
BristolSU\ControlDB\Models\Tags\UserTag Class Reference
Public Member Functions
id ()
name ()
description ()
reference ()
categoryId ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
setTagCategoryId ($categoryId)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\Tags\UserTag
category ()
fullReference ()
users ()
setTagCategoryId (int $categoryId)
addUser (User $user)
removeUser (User $user)
Static Protected Member Functions
static boot ()
Protected Attributes
$table = 'control_tags'
$fillable
Detailed Description
Class UserTag
Definition at line 13 of file UserTag.php.
Member Function Documentation
boot()
static BristolSU\ControlDB\Models\Tags\UserTag::boot () static protected
Boot the model
Add a global scope to only return user tags
Definition at line 22 of file UserTag.php.
categoryId()
BristolSU\ControlDB\Models\Tags\UserTag::categoryId ()
ID of the tag category
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTag.
Definition at line 90 of file UserTag.php.
description()
BristolSU\ControlDB\Models\Tags\UserTag::description ()
Description of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTag.
Definition at line 70 of file UserTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\UserTag\setDescription().
id()
BristolSU\ControlDB\Models\Tags\UserTag::id ()
ID of the user tag
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTag.
Definition at line 50 of file UserTag.php.
name()
BristolSU\ControlDB\Models\Tags\UserTag::name ()
Name of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTag.
Definition at line 60 of file UserTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\UserTag\setName().
reference()
BristolSU\ControlDB\Models\Tags\UserTag::reference ()
Reference of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTag.
Definition at line 80 of file UserTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\UserTag\setReference().
setDescription()
BristolSU\ControlDB\Models\Tags\UserTag::setDescription (string $description)
Set the description of the tagTag Reference
Parameters
string $description
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTag.
Definition at line 111 of file UserTag.php.
References BristolSU\ControlDB\Models\Tags\UserTag\description().
setName()
BristolSU\ControlDB\Models\Tags\UserTag::setName (string $name)
Set the name of the tag
Parameters
string $name
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTag.
Definition at line 100 of file UserTag.php.
References BristolSU\ControlDB\Models\Tags\UserTag\name().
setReference()
BristolSU\ControlDB\Models\Tags\UserTag::setReference (string $reference)
Set the reference of the tag
Parameters
string $reference
Implements BristolSU\ControlDB\Contracts\Models\Tags\UserTag.
Definition at line 122 of file UserTag.php.
References BristolSU\ControlDB\Models\Tags\UserTag\reference().
setTagCategoryId()
BristolSU\ControlDB\Models\Tags\UserTag::setTagCategoryId ($categoryId)
Set the tag category ID
Parameters
int $categoryId
Definition at line 133 of file UserTag.php.
Member Data Documentation
$fillable
BristolSU\ControlDB\Models\Tags\UserTag::$fillable protected
Initial value:
= [
        'name', 'description', 'reference', 'tag_category_id'
    ]
Definition at line 40 of file UserTag.php.
$table
BristolSU\ControlDB\Models\Tags\UserTag::$table = 'control_tags' protected
Definition at line 33 of file UserTag.php.
The documentation for this class was generated from the following file:
src/Models/Tags/UserTag.php