Bristol SU Control: BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController Class Reference
BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController Class Reference
Public Member Functions
index (GroupTagRepository $groupTagRepository)
show (GroupTag $groupTag)
store (GroupTagStoreRequest $request, GroupTagRepository $groupTagRepository)
update (GroupTag $groupTag, GroupTagUpdateRequest $request)
destroy (GroupTag $groupTag, GroupTagRepository $groupTagRepository)
Detailed Description
Handle group tags
Definition at line 14 of file GroupTagController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController::destroy (GroupTag $groupTag, GroupTagRepository $groupTagRepository)
Delete a group tag
Parameters
GroupTag $groupTag
GroupTagRepository $groupTagRepository
Definition at line 87 of file GroupTagController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\id().
index()
BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController::index (GroupTagRepository $groupTagRepository)
Get all group tags
Parameters
GroupTagRepository $groupTagRepository
Returns
GroupTag[]|
Definition at line 23 of file GroupTagController.php.
show()
BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController::show (GroupTag $groupTag)
Show information about a single group tag
Parameters
GroupTag $groupTag
Returns
GroupTag
Definition at line 34 of file GroupTagController.php.
store()
BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController::store (GroupTagStoreRequest $request, GroupTagRepository $groupTagRepository)
Create a new group tag
Parameters
GroupTagStoreRequest $request
GroupTagRepository $groupTagRepository
Returns
GroupTag
Definition at line 46 of file GroupTagController.php.
update()
BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController::update (GroupTag $groupTag, GroupTagUpdateRequest $request)
Update a group tag
Parameters
GroupTag $groupTag
GroupTagUpdateRequest $request
Returns
GroupTag
Definition at line 63 of file GroupTagController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\setDescription(), BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\setName(), BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\setReference(), and BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\setTagCategoryId().
The documentation for this class was generated from the following file:
src/Http/Controllers/GroupTag/GroupTagController.php