Bristol SU Control: BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagGroupController Class Reference
BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagGroupController Class Reference
Public Member Functions
index (GroupTag $groupTag)
update (GroupTag $groupTag, Group $group)
destroy (GroupTag $groupTag, Group $group)
Detailed Description
Handle the link between a group tag and a group
Definition at line 12 of file GroupTagGroupController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagGroupController::destroy (GroupTag $groupTag, Group $group)
Remove the group from the tag
Parameters
GroupTag $groupTag
Group $group
Definition at line 42 of file GroupTagGroupController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\removeGroup().
index()
BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagGroupController::index (GroupTag $groupTag)
Get all groups with the given tag
Parameters
GroupTag $groupTag
Returns
Definition at line 20 of file GroupTagGroupController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\groups().
update()
BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagGroupController::update (GroupTag $groupTag, Group $group)
Add the group to the tag
Parameters
GroupTag $groupTag
Group $group
Definition at line 31 of file GroupTagGroupController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\addGroup().
The documentation for this class was generated from the following file:
src/Http/Controllers/GroupTag/GroupTagGroupController.php