Bristol SU Control: BristolSU\ControlDB\Traits\Tags\GroupTagTrait Class Reference
BristolSU\ControlDB\Traits\Tags\GroupTagTrait Class Reference
Public Member Functions
category ()
fullReference ()
groups ()
addGroup (Group $group)
removeGroup (Group $group)
Detailed Description
Definition at line 10 of file GroupTagTrait.php.
Member Function Documentation
addGroup()
BristolSU\ControlDB\Traits\Tags\GroupTagTrait::addGroup (Group $group)
Definition at line 39 of file GroupTagTrait.php.
category()
BristolSU\ControlDB\Traits\Tags\GroupTagTrait::category ()
Definition at line 13 of file GroupTagTrait.php.
References BristolSU\ControlDB\Contracts\Repositories\Tags\GroupTagCategory\getById().
Referenced by BristolSU\ControlDB\Traits\Tags\GroupTagTrait\fullReference().
fullReference()
BristolSU\ControlDB\Traits\Tags\GroupTagTrait::fullReference ()
Full reference of the tag
This should be the tag category reference and the tag reference, separated with a period.
Returns
string
Definition at line 24 of file GroupTagTrait.php.
References BristolSU\ControlDB\Traits\Tags\GroupTagTrait\category().
groups()
BristolSU\ControlDB\Traits\Tags\GroupTagTrait::groups ()
Groups who have this tag
Returns
Collection
Definition at line 34 of file GroupTagTrait.php.
removeGroup()
BristolSU\ControlDB\Traits\Tags\GroupTagTrait::removeGroup (Group $group)
Definition at line 44 of file GroupTagTrait.php.
The documentation for this class was generated from the following file:
src/Traits/Tags/GroupTagTrait.php