Bristol SU Control: BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag Class Reference
BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag Class Reference
Public Member Functions
addTagToGroup (GroupTag $groupTag, Group $group)
removeTagFromGroup (GroupTag $groupTag, Group $group)
getTagsThroughGroup (Group $group)
getGroupsThroughTag (GroupTag $groupTag)
Detailed Description
Handles the tagging of groups
Definition at line 13 of file GroupGroupTag.php.
Member Function Documentation
addTagToGroup()
BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag::addTagToGroup (GroupTag $groupTag, Group $group)
Tag a group
Parameters
GroupTag $groupTag Tag to tag the group with
Group $group Group to tag
Returns
void
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\GroupGroupTag.
Definition at line 23 of file GroupGroupTag.php.
References BristolSU\ControlDB\Contracts\Models\Group\id(), and BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\id().
getGroupsThroughTag()
BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag::getGroupsThroughTag (GroupTag $groupTag)
Get all groups tagged with a tag
Parameters
GroupTag $groupTag Tag to use to retrieve groups
Returns
Collection|Group[] Groups tagged with the given tag
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\GroupGroupTag.
Definition at line 68 of file GroupGroupTag.php.
References BristolSU\ControlDB\Contracts\Models\Group\id(), and BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\id().
getTagsThroughGroup()
BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag::getTagsThroughGroup (Group $group)
Get all tags a group is tagged with
Parameters
Group $group Group to retrieve tags from
Returns
Collection|GroupTag[] Tags the group is tagged with
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\GroupGroupTag.
Definition at line 50 of file GroupGroupTag.php.
References BristolSU\ControlDB\Contracts\Models\Group\id(), and BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\id().
removeTagFromGroup()
BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag::removeTagFromGroup (GroupTag $groupTag, Group $group)
Remove a tag from a group
Parameters
GroupTag $groupTag Tag to remove from the group
Group $group Group to remove the tag from
Returns
void
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\GroupGroupTag.
Definition at line 37 of file GroupGroupTag.php.
References BristolSU\ControlDB\Contracts\Models\Group\id(), and BristolSU\ControlDB\Contracts\Models\Tags\GroupTag\id().
The documentation for this class was generated from the following file:
src/Repositories/Pivots/Tags/GroupGroupTag.php