Bristol SU Control: BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController Class Reference
BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController Class Reference
Public Member Functions
index (UserTagRepository $userTagRepository)
show (UserTag $userTag)
store (UserTagStoreRequest $request, UserTagRepository $userTagRepository)
update (UserTag $userTag, UserTagUpdateRequest $request)
destroy (UserTag $userTag, UserTagRepository $userTagRepository)
Detailed Description
Handle user tags
Definition at line 14 of file UserTagController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController::destroy (UserTag $userTag, UserTagRepository $userTagRepository)
Delete a user tag
Parameters
UserTag $userTag
UserTagRepository $userTagRepository
Definition at line 87 of file UserTagController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\id().
index()
BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController::index (UserTagRepository $userTagRepository)
Get all user tags
Parameters
UserTagRepository $userTagRepository
Returns
UserTag[]|
Definition at line 23 of file UserTagController.php.
show()
BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController::show (UserTag $userTag)
Show information about a single user tag
Parameters
UserTag $userTag
Returns
UserTag
Definition at line 34 of file UserTagController.php.
store()
BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController::store (UserTagStoreRequest $request, UserTagRepository $userTagRepository)
Create a new user tag
Parameters
UserTagStoreRequest $request
UserTagRepository $userTagRepository
Returns
UserTag
Definition at line 46 of file UserTagController.php.
update()
BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController::update (UserTag $userTag, UserTagUpdateRequest $request)
Update a user tag
Parameters
UserTag $userTag
UserTagUpdateRequest $request
Returns
UserTag
Definition at line 63 of file UserTagController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\setDescription(), BristolSU\ControlDB\Contracts\Models\Tags\UserTag\setName(), BristolSU\ControlDB\Contracts\Models\Tags\UserTag\setReference(), and BristolSU\ControlDB\Contracts\Models\Tags\UserTag\setTagCategoryId().
The documentation for this class was generated from the following file:
src/Http/Controllers/UserTag/UserTagController.php