Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Group\GroupGroupTagController Class Reference
BristolSU\ControlDB\Http\Controllers\Group\GroupGroupTagController Class Reference
Public Member Functions
index (Group $group)
update (Group $group, GroupTag $groupTag)
destroy (Group $group, GroupTag $groupTag)
Detailed Description
Handles a group tags link to a group
Definition at line 12 of file GroupGroupTagController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Group\GroupGroupTagController::destroy (Group $group, GroupTag $groupTag)
Remove a tag from a group
Parameters
Group $group
GroupTag $groupTag
Definition at line 43 of file GroupGroupTagController.php.
References BristolSU\ControlDB\Contracts\Models\Group\removeTag().
index()
BristolSU\ControlDB\Http\Controllers\Group\GroupGroupTagController::index (Group $group)
Get all group tags through a group
Parameters
Group $group
Returns
Definition at line 21 of file GroupGroupTagController.php.
References BristolSU\ControlDB\Contracts\Models\Group\tags().
update()
BristolSU\ControlDB\Http\Controllers\Group\GroupGroupTagController::update (Group $group, GroupTag $groupTag)
Tag a group
Parameters
Group $group
GroupTag $groupTag
Definition at line 32 of file GroupGroupTagController.php.
References BristolSU\ControlDB\Contracts\Models\Group\addTag().
The documentation for this class was generated from the following file:
src/Http/Controllers/Group/GroupGroupTagController.php