Bristol SU Control: BristolSU\ControlDB\Http\Controllers\GroupTagCategory\GroupTagCategoryController Class Reference
BristolSU\ControlDB\Http\Controllers\GroupTagCategory\GroupTagCategoryController Class Reference
Public Member Functions
index (GroupTagCategoryRepository $groupTagCategoryRepository)
show (GroupTagCategory $groupTagCategory)
store (GroupTagCategoryStoreRequest $request, GroupTagCategoryRepository $groupTagCategoryRepository)
update (GroupTagCategory $groupTagCategory, GroupTagCategoryUpdateRequest $request)
destroy (GroupTagCategory $groupTagCategory, GroupTagCategoryRepository $groupTagCategoryRepository)
Public Member Functions inherited from BristolSU\ControlDB\Http\Controllers\Controller
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Handle group tag categories
Definition at line 14 of file GroupTagCategoryController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\GroupTagCategory\GroupTagCategoryController::destroy (GroupTagCategory $groupTagCategory, GroupTagCategoryRepository $groupTagCategoryRepository)
Delete a tag category
Parameters
GroupTagCategory $groupTagCategory
GroupTagCategoryRepository $groupTagCategoryRepository
Definition at line 81 of file GroupTagCategoryController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory\id().
index()
BristolSU\ControlDB\Http\Controllers\GroupTagCategory\GroupTagCategoryController::index (GroupTagCategoryRepository $groupTagCategoryRepository)
Get all group tag categories
Parameters
GroupTagCategoryRepository $groupTagCategoryRepository
Returns
Definition at line 21 of file GroupTagCategoryController.php.
References BristolSU\ControlDB\Http\Controllers\Controller\paginate().
show()
BristolSU\ControlDB\Http\Controllers\GroupTagCategory\GroupTagCategoryController::show (GroupTagCategory $groupTagCategory)
Get information about a single tag category
Parameters
GroupTagCategory $groupTagCategory
Returns
GroupTagCategory
Definition at line 32 of file GroupTagCategoryController.php.
store()
BristolSU\ControlDB\Http\Controllers\GroupTagCategory\GroupTagCategoryController::store (GroupTagCategoryStoreRequest $request, GroupTagCategoryRepository $groupTagCategoryRepository)
Create a new tag category
Parameters
GroupTagCategoryStoreRequest $request
GroupTagCategoryRepository $groupTagCategoryRepository
Returns
GroupTagCategory
Definition at line 44 of file GroupTagCategoryController.php.
update()
BristolSU\ControlDB\Http\Controllers\GroupTagCategory\GroupTagCategoryController::update (GroupTagCategory $groupTagCategory, GroupTagCategoryUpdateRequest $request)
Update a tag category
Parameters
GroupTagCategory $groupTagCategory
GroupTagCategoryUpdateRequest $request
Returns
GroupTagCategory
Definition at line 60 of file GroupTagCategoryController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory\setDescription(), BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory\setName(), and BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory\setReference().
The documentation for this class was generated from the following file:
src/Http/Controllers/GroupTagCategory/GroupTagCategoryController.php