Bristol SU Control: BristolSU\ControlDB\Traits\Tags\UserTagTrait Class Reference
BristolSU\ControlDB\Traits\Tags\UserTagTrait Class Reference
Public Member Functions
fullReference ()
category ()
users ()
addUser (User $user)
removeUser (User $user)
Detailed Description
Definition at line 10 of file UserTagTrait.php.
Member Function Documentation
addUser()
BristolSU\ControlDB\Traits\Tags\UserTagTrait::addUser (User $user)
Definition at line 44 of file UserTagTrait.php.
category()
BristolSU\ControlDB\Traits\Tags\UserTagTrait::category ()
Tag Category
Returns
UserTagCategory
Definition at line 29 of file UserTagTrait.php.
References BristolSU\ControlDB\Contracts\Repositories\Tags\UserTagCategory\getById().
Referenced by BristolSU\ControlDB\Traits\Tags\UserTagTrait\fullReference().
fullReference()
BristolSU\ControlDB\Traits\Tags\UserTagTrait::fullReference ()
Full reference of the tag
This should be the tag category reference and the tag reference, separated with a period.
Returns
string
Definition at line 19 of file UserTagTrait.php.
References BristolSU\ControlDB\Traits\Tags\UserTagTrait\category().
removeUser()
BristolSU\ControlDB\Traits\Tags\UserTagTrait::removeUser (User $user)
Definition at line 49 of file UserTagTrait.php.
users()
BristolSU\ControlDB\Traits\Tags\UserTagTrait::users ()
Users who have this tag
Returns
Collection
Definition at line 39 of file UserTagTrait.php.
The documentation for this class was generated from the following file:
src/Traits/Tags/UserTagTrait.php