Bristol SU Control: BristolSU\ControlDB\Export\Handler\UsesCsv Class Reference
BristolSU\ControlDB\Export\Handler\UsesCsv Class Reference
Public Member Functions
getHeaders ($items)
getRows ($items, $headers=null, $defaultIfNull=null)
generateCsv ($items, $defaultIfNull=null)
Detailed Description
Definition at line 8 of file UsesCsv.php.
Member Function Documentation
generateCsv()
BristolSU\ControlDB\Export\Handler\UsesCsv::generateCsv ($items, $defaultIfNull = null)
Definition at line 50 of file UsesCsv.php.
References BristolSU\ControlDB\Export\Handler\UsesCsv\getHeaders(), and BristolSU\ControlDB\Export\Handler\UsesCsv\getRows().
Referenced by BristolSU\ControlDB\Export\Handler\SaveCsvHandler\save().
getHeaders()
BristolSU\ControlDB\Export\Handler\UsesCsv::getHeaders ($items)
Parameters
array|FormattedItem[] $items
Returns
array
Definition at line 15 of file UsesCsv.php.
Referenced by BristolSU\ControlDB\Export\Handler\UsesCsv\generateCsv(), and BristolSU\ControlDB\Export\Handler\UsesCsv\getRows().
getRows()
BristolSU\ControlDB\Export\Handler\UsesCsv::getRows ($items, $headers = null, $defaultIfNull = null)
Parameters
array|FormattedItem[] $items
null $headers
$defaultIfNull
Returns
array
Definition at line 34 of file UsesCsv.php.
References BristolSU\ControlDB\Export\Handler\UsesCsv\getHeaders().
Referenced by BristolSU\ControlDB\Export\Handler\UsesCsv\generateCsv().
The documentation for this class was generated from the following file:
src/Export/Handler/UsesCsv.php