Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Role\RoleController Class Reference
BristolSU\ControlDB\Http\Controllers\Role\RoleController Class Reference
Public Member Functions
index (RoleRepository $roleRepository)
show (Role $role)
store (StoreRoleRequest $request, RoleRepository $roleRepository, DataRoleRepository $dataRoleRepository)
update (Role $role, UpdateRoleRequest $request, RoleRepository $roleRepository, DataRoleRepository $dataRoleRepository)
destroy (Role $role, RoleRepository $roleRepository)
Detailed Description
Handle roles
Definition at line 15 of file RoleController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Role\RoleController::destroy (Role $role, RoleRepository $roleRepository)
Delete a role
Parameters
Role $role
RoleRepository $roleRepository
Definition at line 95 of file RoleController.php.
References BristolSU\ControlDB\Contracts\Models\Role\id().
index()
BristolSU\ControlDB\Http\Controllers\Role\RoleController::index (RoleRepository $roleRepository)
Get all roles
Parameters
RoleRepository $roleRepository
Returns
Role[]|
Definition at line 24 of file RoleController.php.
show()
BristolSU\ControlDB\Http\Controllers\Role\RoleController::show (Role $role)
Get information about a specific role
Parameters
Role $role
Returns
Role
Definition at line 35 of file RoleController.php.
store()
BristolSU\ControlDB\Http\Controllers\Role\RoleController::store (StoreRoleRequest $request, RoleRepository $roleRepository, DataRoleRepository $dataRoleRepository)
Create a new role
Parameters
StoreRoleRequest $request
RoleRepository $roleRepository
DataRoleRepository $dataRoleRepository
Returns
Role
Definition at line 48 of file RoleController.php.
update()
BristolSU\ControlDB\Http\Controllers\Role\RoleController::update (Role $role, UpdateRoleRequest $request, RoleRepository $roleRepository, DataRoleRepository $dataRoleRepository)
Update a role
Parameters
Role $role
UpdateRoleRequest $request
RoleRepository $roleRepository
DataRoleRepository $dataRoleRepository
Returns
Role
Definition at line 67 of file RoleController.php.
References BristolSU\ControlDB\Contracts\Models\Role\data(), BristolSU\ControlDB\Contracts\Models\Role\setGroupId(), and BristolSU\ControlDB\Contracts\Models\Role\setPositionId().
The documentation for this class was generated from the following file:
src/Http/Controllers/Role/RoleController.php