Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Position\PositionPositionTagController Class Reference
BristolSU\ControlDB\Http\Controllers\Position\PositionPositionTagController Class Reference
Public Member Functions
index (Position $position)
update (Position $position, PositionTag $positionTag)
destroy (Position $position, PositionTag $positionTag)
Public Member Functions inherited from BristolSU\ControlDB\Http\Controllers\Controller
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Handle the tagging and untagging of positions
Definition at line 12 of file PositionPositionTagController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Position\PositionPositionTagController::destroy (Position $position, PositionTag $positionTag)
Untag position
Parameters
Position $position
PositionTag $positionTag
Definition at line 43 of file PositionPositionTagController.php.
References BristolSU\ControlDB\Contracts\Models\Position\removeTag().
index()
BristolSU\ControlDB\Http\Controllers\Position\PositionPositionTagController::index (Position $position)
Get all tags belonging to the current position
Parameters
Position $position
Returns
Definition at line 21 of file PositionPositionTagController.php.
References BristolSU\ControlDB\Http\Controllers\Controller\paginate(), and BristolSU\ControlDB\Contracts\Models\Position\tags().
update()
BristolSU\ControlDB\Http\Controllers\Position\PositionPositionTagController::update (Position $position, PositionTag $positionTag)
Tag a position
Parameters
Position $position
PositionTag $positionTag
Definition at line 32 of file PositionPositionTagController.php.
References BristolSU\ControlDB\Contracts\Models\Position\addTag().
The documentation for this class was generated from the following file:
src/Http/Controllers/Position/PositionPositionTagController.php