Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Api\UserTagCategory\UserTagCategoryController Class Reference
BristolSU\ControlDB\Http\Controllers\Api\UserTagCategory\UserTagCategoryController Class Reference
Public Member Functions
index (UserTagCategoryRepository $userTagCategoryRepository)
show (UserTagCategory $userTagCategory)
store (UserTagCategoryStoreRequest $request, UserTagCategoryRepository $userTagCategoryRepository)
update (UserTagCategory $userTagCategory, UserTagCategoryUpdateRequest $request)
destroy (UserTagCategory $userTagCategory, UserTagCategoryRepository $userTagCategoryRepository)
Detailed Description
Definition at line 11 of file UserTagCategoryController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Api\UserTagCategory\UserTagCategoryController::destroy (UserTagCategory $userTagCategory, UserTagCategoryRepository $userTagCategoryRepository)
Definition at line 48 of file UserTagCategoryController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory\id().
index()
BristolSU\ControlDB\Http\Controllers\Api\UserTagCategory\UserTagCategoryController::index (UserTagCategoryRepository $userTagCategoryRepository)
Definition at line 14 of file UserTagCategoryController.php.
show()
BristolSU\ControlDB\Http\Controllers\Api\UserTagCategory\UserTagCategoryController::show (UserTagCategory $userTagCategory)
Definition at line 19 of file UserTagCategoryController.php.
store()
BristolSU\ControlDB\Http\Controllers\Api\UserTagCategory\UserTagCategoryController::store (UserTagCategoryStoreRequest $request, UserTagCategoryRepository $userTagCategoryRepository)
Definition at line 24 of file UserTagCategoryController.php.
update()
BristolSU\ControlDB\Http\Controllers\Api\UserTagCategory\UserTagCategoryController::update (UserTagCategory $userTagCategory, UserTagCategoryUpdateRequest $request)
Definition at line 33 of file UserTagCategoryController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory\setDescription(), BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory\setName(), and BristolSU\ControlDB\Contracts\Models\Tags\UserTagCategory\setReference().
The documentation for this class was generated from the following file:
src/Http/Controllers/Api/UserTagCategory/UserTagCategoryController.php