Bristol SU Control: BristolSU\ControlDB\Models\DataGroup Class Reference
BristolSU\ControlDB\Models\DataGroup Class Reference
Public Member Functions
id ()
name ()
email ()
setName (?string $name)
setEmail (?string $email)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\DataGroup
group ()
Public Member Functions inherited from BristolSU\ControlDB\AdditionalProperties\ImplementsAdditionalProperties
getAdditionalAttribute (string $key)
setAdditionalAttribute (string $key, $value)
Protected Attributes
$table = 'control_data_group'
$fillable
Additional Inherited Members
Static Public Member Functions inherited from BristolSU\ControlDB\AdditionalProperties\ImplementsAdditionalProperties
static addProperty (string $key)
Detailed Description
Represents a data group, information to attach to a group such as a name
Definition at line 13 of file DataGroup.php.
Member Function Documentation
email()
BristolSU\ControlDB\Models\DataGroup::email ()
Gets the email of the group
Returns
string|null
Implements BristolSU\ControlDB\Contracts\Models\DataGroup.
Definition at line 58 of file DataGroup.php.
Referenced by BristolSU\ControlDB\Models\DataGroup\setEmail().
id()
BristolSU\ControlDB\Models\DataGroup::id ()
Gets the ID of the group
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\DataGroup.
Definition at line 38 of file DataGroup.php.
name()
BristolSU\ControlDB\Models\DataGroup::name ()
Gets the name of the group
Returns
string|null
Implements BristolSU\ControlDB\Contracts\Models\DataGroup.
Definition at line 48 of file DataGroup.php.
Referenced by BristolSU\ControlDB\Models\DataGroup\setName().
setEmail()
BristolSU\ControlDB\Models\DataGroup::setEmail (?string $email)
Set the email of the group
Parameters
string | null $email
Implements BristolSU\ControlDB\Contracts\Models\DataGroup.
Definition at line 79 of file DataGroup.php.
References BristolSU\ControlDB\Models\DataGroup\email().
setName()
BristolSU\ControlDB\Models\DataGroup::setName (?string $name)
Set the name of the group
Parameters
string | null $name
Implements BristolSU\ControlDB\Contracts\Models\DataGroup.
Definition at line 68 of file DataGroup.php.
References BristolSU\ControlDB\Models\DataGroup\name().
Member Data Documentation
$fillable
BristolSU\ControlDB\Models\DataGroup::$fillable protected
Initial value:
= [
        'name', 'email'
    ]
Definition at line 29 of file DataGroup.php.
$table
BristolSU\ControlDB\Models\DataGroup::$table = 'control_data_group' protected
Definition at line 22 of file DataGroup.php.
The documentation for this class was generated from the following file:
src/Models/DataGroup.php