Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Role\RoleRoleTagController Class Reference
BristolSU\ControlDB\Http\Controllers\Role\RoleRoleTagController Class Reference
Public Member Functions
index (Role $role)
update (Role $role, RoleTag $roleTag)
destroy (Role $role, RoleTag $roleTag)
Public Member Functions inherited from BristolSU\ControlDB\Http\Controllers\Controller
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Handle the tagging and untagging of roles
Definition at line 12 of file RoleRoleTagController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Role\RoleRoleTagController::destroy (Role $role, RoleTag $roleTag)
Untag role
Parameters
Role $role
RoleTag $roleTag
Definition at line 43 of file RoleRoleTagController.php.
References BristolSU\ControlDB\Contracts\Models\Role\removeTag().
index()
BristolSU\ControlDB\Http\Controllers\Role\RoleRoleTagController::index (Role $role)
Get all tags belonging to the current role
Parameters
Role $role
Returns
Definition at line 21 of file RoleRoleTagController.php.
References BristolSU\ControlDB\Http\Controllers\Controller\paginate(), and BristolSU\ControlDB\Contracts\Models\Role\tags().
update()
BristolSU\ControlDB\Http\Controllers\Role\RoleRoleTagController::update (Role $role, RoleTag $roleTag)
Tag a role
Parameters
Role $role
RoleTag $roleTag
Definition at line 32 of file RoleRoleTagController.php.
References BristolSU\ControlDB\Contracts\Models\Role\addTag().
The documentation for this class was generated from the following file:
src/Http/Controllers/Role/RoleRoleTagController.php