Bristol SU Control: BristolSU\ControlDB\Export\ExportManager Class Reference
BristolSU\ControlDB\Export\ExportManager Class Reference
Public Member Functions
__construct (Container $container)
driver ($driver=null)
getDefaultDriver ()
extend ($driver, Closure $callback)
withFormatter (string $formatter, array $config=[])
__call ($method, $parameters)
createDumpDriver (array $config)
createSaveCsvDriver (array $config)
Protected Member Functions
resolve ($name)
callCustomCreator (array $config)
configurationFor ($name)
formatters ()
Protected Attributes
$container
$customCreators = []
$formatters = []
Detailed Description
Definition at line 13 of file ExportManager.php.
Constructor & Destructor Documentation
__construct()
BristolSU\ControlDB\Export\ExportManager::__construct (Container $container)
Create a new Export manager instance.
Parameters
Container $container
Returns
void
Definition at line 38 of file ExportManager.php.
References BristolSU\ControlDB\Export\ExportManager\$container.
Member Function Documentation
__call()
BristolSU\ControlDB\Export\ExportManager::__call ($method, $parameters)
Dynamically call the default driver instance.
Parameters
string $method
array $parameters
Returns
mixed
Definition at line 153 of file ExportManager.php.
References BristolSU\ControlDB\Export\ExportManager\driver().
callCustomCreator()
BristolSU\ControlDB\Export\ExportManager::callCustomCreator (array $config) protected
Call a custom driver creator.
Parameters
array $config
Returns
mixed
Definition at line 88 of file ExportManager.php.
References BristolSU\ControlDB\Export\ExportManager\$container.
Referenced by BristolSU\ControlDB\Export\ExportManager\resolve().
configurationFor()
BristolSU\ControlDB\Export\ExportManager::configurationFor ($name) protected
Get the export connection configuration.
Parameters
string $name
Returns
array
Definition at line 99 of file ExportManager.php.
References BristolSU\ControlDB\Export\ExportManager\formatters().
Referenced by BristolSU\ControlDB\Export\ExportManager\resolve().
createDumpDriver()
BristolSU\ControlDB\Export\ExportManager::createDumpDriver (array $config)
Definition at line 158 of file ExportManager.php.
createSaveCsvDriver()
BristolSU\ControlDB\Export\ExportManager::createSaveCsvDriver (array $config)
Definition at line 163 of file ExportManager.php.
driver()
BristolSU\ControlDB\Export\ExportManager::driver ($driver = null)
Get a export driver instance.
Parameters
string | null $driver
Returns
mixed
Definition at line 49 of file ExportManager.php.
References BristolSU\ControlDB\Export\ExportManager\getDefaultDriver(), and BristolSU\ControlDB\Export\ExportManager\resolve().
Referenced by BristolSU\ControlDB\Export\ExportManager\__call().
extend()
BristolSU\ControlDB\Export\ExportManager::extend ($driver, Closure $callback)
Register a custom driver creator Closure.
Parameters
string $driver
\Closure $callback
Returns
$this
Definition at line 132 of file ExportManager.php.
formatters()
BristolSU\ControlDB\Export\ExportManager::formatters () protected
Definition at line 168 of file ExportManager.php.
References BristolSU\ControlDB\Export\ExportManager\$formatters.
Referenced by BristolSU\ControlDB\Export\ExportManager\configurationFor(), and BristolSU\ControlDB\Export\ExportManager\withFormatter().
getDefaultDriver()
BristolSU\ControlDB\Export\ExportManager::getDefaultDriver ()
Get the default export driver name.
Returns
string
Definition at line 120 of file ExportManager.php.
Referenced by BristolSU\ControlDB\Export\ExportManager\driver().
resolve()
BristolSU\ControlDB\Export\ExportManager::resolve ($name) protected
Resolve the given export instance by name.
Parameters
string $name
Returns
Handler
Exceptions
Definition at line 62 of file ExportManager.php.
References BristolSU\ControlDB\Export\ExportManager\callCustomCreator(), and BristolSU\ControlDB\Export\ExportManager\configurationFor().
Referenced by BristolSU\ControlDB\Export\ExportManager\driver().
withFormatter()
BristolSU\ControlDB\Export\ExportManager::withFormatter (string $formatter, array $config = [])
Definition at line 139 of file ExportManager.php.
References BristolSU\ControlDB\Export\ExportManager\formatters().
Member Data Documentation
$container
BristolSU\ControlDB\Export\ExportManager::$container protected
Definition at line 21 of file ExportManager.php.
Referenced by BristolSU\ControlDB\Export\ExportManager\__construct(), and BristolSU\ControlDB\Export\ExportManager\callCustomCreator().
$customCreators
BristolSU\ControlDB\Export\ExportManager::$customCreators = [] protected
Definition at line 28 of file ExportManager.php.
$formatters
BristolSU\ControlDB\Export\ExportManager::$formatters = [] protected
Definition at line 30 of file ExportManager.php.
Referenced by BristolSU\ControlDB\Export\ExportManager\formatters().
The documentation for this class was generated from the following file:
src/Export/ExportManager.php