Bristol SU Control: BristolSU\ControlDB\Http\Controllers\RoleTagCategory\RoleTagCategoryController Class Reference
BristolSU\ControlDB\Http\Controllers\RoleTagCategory\RoleTagCategoryController Class Reference
Public Member Functions
index (RoleTagCategoryRepository $roleTagCategoryRepository)
show (RoleTagCategory $roleTagCategory)
store (RoleTagCategoryStoreRequest $request, RoleTagCategoryRepository $roleTagCategoryRepository)
update (RoleTagCategory $roleTagCategory, RoleTagCategoryUpdateRequest $request)
destroy (RoleTagCategory $roleTagCategory, RoleTagCategoryRepository $roleTagCategoryRepository)
Public Member Functions inherited from BristolSU\ControlDB\Http\Controllers\Controller
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Handle role tag categories
Definition at line 14 of file RoleTagCategoryController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\RoleTagCategory\RoleTagCategoryController::destroy (RoleTagCategory $roleTagCategory, RoleTagCategoryRepository $roleTagCategoryRepository)
Delete a tag category
Parameters
RoleTagCategory $roleTagCategory
RoleTagCategoryRepository $roleTagCategoryRepository
Definition at line 81 of file RoleTagCategoryController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory\id().
index()
BristolSU\ControlDB\Http\Controllers\RoleTagCategory\RoleTagCategoryController::index (RoleTagCategoryRepository $roleTagCategoryRepository)
Get all role tag categories
Parameters
RoleTagCategoryRepository $roleTagCategoryRepository
Returns
Definition at line 21 of file RoleTagCategoryController.php.
References BristolSU\ControlDB\Http\Controllers\Controller\paginate().
show()
BristolSU\ControlDB\Http\Controllers\RoleTagCategory\RoleTagCategoryController::show (RoleTagCategory $roleTagCategory)
Get information about a single tag category
Parameters
RoleTagCategory $roleTagCategory
Returns
RoleTagCategory
Definition at line 32 of file RoleTagCategoryController.php.
store()
BristolSU\ControlDB\Http\Controllers\RoleTagCategory\RoleTagCategoryController::store (RoleTagCategoryStoreRequest $request, RoleTagCategoryRepository $roleTagCategoryRepository)
Create a new tag category
Parameters
RoleTagCategoryStoreRequest $request
RoleTagCategoryRepository $roleTagCategoryRepository
Returns
RoleTagCategory
Definition at line 44 of file RoleTagCategoryController.php.
update()
BristolSU\ControlDB\Http\Controllers\RoleTagCategory\RoleTagCategoryController::update (RoleTagCategory $roleTagCategory, RoleTagCategoryUpdateRequest $request)
Update a tag category
Parameters
RoleTagCategory $roleTagCategory
RoleTagCategoryUpdateRequest $request
Returns
RoleTagCategory
Definition at line 60 of file RoleTagCategoryController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory\setDescription(), BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory\setName(), and BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory\setReference().
The documentation for this class was generated from the following file:
src/Http/Controllers/RoleTagCategory/RoleTagCategoryController.php