Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Api\Group\GroupGroupTagController Class Reference
BristolSU\ControlDB\Http\Controllers\Api\Group\GroupGroupTagController Class Reference
Public Member Functions
index (Group $group)
update (Group $group, GroupTag $groupTag)
destroy (Group $group, GroupTag $groupTag)
Detailed Description
Definition at line 9 of file GroupGroupTagController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Api\Group\GroupGroupTagController::destroy (Group $group, GroupTag $groupTag)
Definition at line 22 of file GroupGroupTagController.php.
References BristolSU\ControlDB\Contracts\Models\Group\removeTag().
index()
BristolSU\ControlDB\Http\Controllers\Api\Group\GroupGroupTagController::index (Group $group)
Definition at line 12 of file GroupGroupTagController.php.
References BristolSU\ControlDB\Contracts\Models\Group\tags().
update()
BristolSU\ControlDB\Http\Controllers\Api\Group\GroupGroupTagController::update (Group $group, GroupTag $groupTag)
Definition at line 17 of file GroupGroupTagController.php.
References BristolSU\ControlDB\Contracts\Models\Group\addTag().
The documentation for this class was generated from the following file:
src/Http/Controllers/Api/Group/GroupGroupTagController.php