Bristol SU Control: BristolSU\ControlDB\Models\Tags\PositionTag Class Reference
BristolSU\ControlDB\Models\Tags\PositionTag Class Reference
Public Member Functions
id ()
name ()
description ()
reference ()
categoryId ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
setTagCategoryId ($categoryId)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\Tags\PositionTag
category ()
fullReference ()
positions ()
setTagCategoryId (int $categoryId)
addPosition (Position $position)
removePosition (Position $position)
Static Protected Member Functions
static boot ()
Protected Attributes
$table = 'control_tags'
$fillable
Detailed Description
Class PositionTag
Definition at line 13 of file PositionTag.php.
Member Function Documentation
boot()
static BristolSU\ControlDB\Models\Tags\PositionTag::boot () static protected
Boot the model
Add a global scope to only return position tags
Definition at line 22 of file PositionTag.php.
categoryId()
BristolSU\ControlDB\Models\Tags\PositionTag::categoryId ()
ID of the tag category
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTag.
Definition at line 90 of file PositionTag.php.
description()
BristolSU\ControlDB\Models\Tags\PositionTag::description ()
Description of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTag.
Definition at line 70 of file PositionTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\PositionTag\setDescription().
id()
BristolSU\ControlDB\Models\Tags\PositionTag::id ()
ID of the position tag
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTag.
Definition at line 50 of file PositionTag.php.
name()
BristolSU\ControlDB\Models\Tags\PositionTag::name ()
Name of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTag.
Definition at line 60 of file PositionTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\PositionTag\setName().
reference()
BristolSU\ControlDB\Models\Tags\PositionTag::reference ()
Reference of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTag.
Definition at line 80 of file PositionTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\PositionTag\setReference().
setDescription()
BristolSU\ControlDB\Models\Tags\PositionTag::setDescription (string $description)
Set the description of the tagTag Reference
Parameters
string $description
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTag.
Definition at line 111 of file PositionTag.php.
References BristolSU\ControlDB\Models\Tags\PositionTag\description().
setName()
BristolSU\ControlDB\Models\Tags\PositionTag::setName (string $name)
Set the name of the tag
Parameters
string $name
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTag.
Definition at line 100 of file PositionTag.php.
References BristolSU\ControlDB\Models\Tags\PositionTag\name().
setReference()
BristolSU\ControlDB\Models\Tags\PositionTag::setReference (string $reference)
Set the reference of the tag
Parameters
string $reference
Implements BristolSU\ControlDB\Contracts\Models\Tags\PositionTag.
Definition at line 122 of file PositionTag.php.
References BristolSU\ControlDB\Models\Tags\PositionTag\reference().
setTagCategoryId()
BristolSU\ControlDB\Models\Tags\PositionTag::setTagCategoryId ($categoryId)
Set the tag category ID
Parameters
int $categoryId
Definition at line 133 of file PositionTag.php.
Member Data Documentation
$fillable
BristolSU\ControlDB\Models\Tags\PositionTag::$fillable protected
Initial value:
= [
        'name', 'description', 'reference', 'tag_category_id'
    ]
Definition at line 40 of file PositionTag.php.
$table
BristolSU\ControlDB\Models\Tags\PositionTag::$table = 'control_tags' protected
Definition at line 33 of file PositionTag.php.
The documentation for this class was generated from the following file:
src/Models/Tags/PositionTag.php