Bristol SU Control: BristolSU\ControlDB\Models\Tags\RoleTagCategory Class Reference
BristolSU\ControlDB\Models\Tags\RoleTagCategory Class Reference
Public Member Functions
id ()
name ()
description ()
reference ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory
tags ()
Static Protected Member Functions
static boot ()
Protected Attributes
$table = 'control_tag_categories'
$fillable
Detailed Description
Role Tag Category
Definition at line 13 of file RoleTagCategory.php.
Member Function Documentation
boot()
static BristolSU\ControlDB\Models\Tags\RoleTagCategory::boot () static protected
Boot the model
Add a scope to only retrieve role tag categories
Definition at line 22 of file RoleTagCategory.php.
description()
BristolSU\ControlDB\Models\Tags\RoleTagCategory::description ()
Deacription of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory.
Definition at line 72 of file RoleTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\RoleTagCategory\setDescription().
id()
BristolSU\ControlDB\Models\Tags\RoleTagCategory::id ()
ID of the tag category
Returns
mixed
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory.
Definition at line 52 of file RoleTagCategory.php.
name()
BristolSU\ControlDB\Models\Tags\RoleTagCategory::name ()
Name of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory.
Definition at line 62 of file RoleTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\RoleTagCategory\setName().
reference()
BristolSU\ControlDB\Models\Tags\RoleTagCategory::reference ()
Reference of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory.
Definition at line 82 of file RoleTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\RoleTagCategory\setReference().
setDescription()
BristolSU\ControlDB\Models\Tags\RoleTagCategory::setDescription (string $description)
Set the description of the tag category
Parameters
string $description
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory.
Definition at line 103 of file RoleTagCategory.php.
References BristolSU\ControlDB\Models\Tags\RoleTagCategory\description().
setName()
BristolSU\ControlDB\Models\Tags\RoleTagCategory::setName (string $name)
Set the name of the tag category
Parameters
string $name
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory.
Definition at line 92 of file RoleTagCategory.php.
References BristolSU\ControlDB\Models\Tags\RoleTagCategory\name().
setReference()
BristolSU\ControlDB\Models\Tags\RoleTagCategory::setReference (string $reference)
Set the reference of the tag category
Parameters
string $reference
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTagCategory.
Definition at line 114 of file RoleTagCategory.php.
References BristolSU\ControlDB\Models\Tags\RoleTagCategory\reference().
Member Data Documentation
$fillable
BristolSU\ControlDB\Models\Tags\RoleTagCategory::$fillable protected
Initial value:
= [
        'name', 'description', 'reference'
    ]
Definition at line 43 of file RoleTagCategory.php.
$table
BristolSU\ControlDB\Models\Tags\RoleTagCategory::$table = 'control_tag_categories' protected
Definition at line 36 of file RoleTagCategory.php.
The documentation for this class was generated from the following file:
src/Models/Tags/RoleTagCategory.php