Bristol SU Control: BristolSU\ControlDB\Repositories\Pivots\UserGroup Class Reference
BristolSU\ControlDB\Repositories\Pivots\UserGroup Class Reference
Public Member Functions
getUsersThroughGroup (Group $group)
getGroupsThroughUser (User $user)
addUserToGroup (User $user, Group $group)
removeUserFromGroup (User $user, Group $group)
Detailed Description
Handle the relationship between a group and a user
Definition at line 13 of file UserGroup.php.
Member Function Documentation
addUserToGroup()
BristolSU\ControlDB\Repositories\Pivots\UserGroup::addUserToGroup (User $user, Group $group)
Add a user to a group
Parameters
User $user User to add to the group
Group $group Group to add the user to
Returns
void
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\UserGroup.
Definition at line 57 of file UserGroup.php.
References BristolSU\ControlDB\Contracts\Models\Group\id(), and BristolSU\ControlDB\Contracts\Models\User\id().
getGroupsThroughUser()
BristolSU\ControlDB\Repositories\Pivots\UserGroup::getGroupsThroughUser (User $user)
Get all groups a user belongs to
Parameters
User $user
Returns
Group[]|Collection Groups the user is a member of
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\UserGroup.
Definition at line 39 of file UserGroup.php.
References BristolSU\ControlDB\Contracts\Models\Group\id(), and BristolSU\ControlDB\Contracts\Models\User\id().
getUsersThroughGroup()
BristolSU\ControlDB\Repositories\Pivots\UserGroup::getUsersThroughGroup (Group $group)
Get all users who are members of a group
Parameters
Group $group
Returns
User[]|Collection Users who are members of the group
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\UserGroup.
Definition at line 22 of file UserGroup.php.
References BristolSU\ControlDB\Contracts\Models\Group\id(), and BristolSU\ControlDB\Contracts\Models\User\id().
removeUserFromGroup()
BristolSU\ControlDB\Repositories\Pivots\UserGroup::removeUserFromGroup (User $user, Group $group)
Remove a user from a group
Parameters
User $user User to remove from the group
Group $group Group to remove the user from
Returns
void
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\UserGroup.
Definition at line 70 of file UserGroup.php.
References BristolSU\ControlDB\Contracts\Models\Group\id(), and BristolSU\ControlDB\Contracts\Models\User\id().
The documentation for this class was generated from the following file:
src/Repositories/Pivots/UserGroup.php