Bristol SU Control: BristolSU\ControlDB\Traits\Tags\RoleTagTrait Class Reference
BristolSU\ControlDB\Traits\Tags\RoleTagTrait Class Reference
Public Member Functions
fullReference ()
category ()
roles ()
addRole (Role $role)
removeRole (Role $role)
Detailed Description
Definition at line 10 of file RoleTagTrait.php.
Member Function Documentation
addRole()
BristolSU\ControlDB\Traits\Tags\RoleTagTrait::addRole (Role $role)
Definition at line 44 of file RoleTagTrait.php.
category()
BristolSU\ControlDB\Traits\Tags\RoleTagTrait::category ()
Tag Category
Returns
RoleTagCategory
Definition at line 29 of file RoleTagTrait.php.
References BristolSU\ControlDB\Contracts\Repositories\Tags\RoleTagCategory\getById().
Referenced by BristolSU\ControlDB\Traits\Tags\RoleTagTrait\fullReference().
fullReference()
BristolSU\ControlDB\Traits\Tags\RoleTagTrait::fullReference ()
Full reference of the tag
This should be the tag category reference and the tag reference, separated with a period.
Returns
string
Definition at line 19 of file RoleTagTrait.php.
References BristolSU\ControlDB\Traits\Tags\RoleTagTrait\category().
removeRole()
BristolSU\ControlDB\Traits\Tags\RoleTagTrait::removeRole (Role $role)
Definition at line 49 of file RoleTagTrait.php.
roles()
BristolSU\ControlDB\Traits\Tags\RoleTagTrait::roles ()
Roles who have this tag
Returns
Collection
Definition at line 39 of file RoleTagTrait.php.
The documentation for this class was generated from the following file:
src/Traits/Tags/RoleTagTrait.php