Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Api\Role\RoleController Class Reference
BristolSU\ControlDB\Http\Controllers\Api\Role\RoleController Class Reference
Public Member Functions
index (RoleRepository $roleRepository)
show (Role $role)
store (StoreRoleRequest $request, RoleRepository $roleRepository, DataRoleRepository $dataRoleRepository)
update (Role $role, UpdateRoleRequest $request, RoleRepository $roleRepository, DataRoleRepository $dataRoleRepository)
destroy (Role $role, RoleRepository $roleRepository)
Detailed Description
Definition at line 12 of file RoleController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Api\Role\RoleController::destroy (Role $role, RoleRepository $roleRepository)
Definition at line 56 of file RoleController.php.
References BristolSU\ControlDB\Contracts\Models\Role\id().
index()
BristolSU\ControlDB\Http\Controllers\Api\Role\RoleController::index (RoleRepository $roleRepository)
Definition at line 14 of file RoleController.php.
show()
BristolSU\ControlDB\Http\Controllers\Api\Role\RoleController::show (Role $role)
Definition at line 19 of file RoleController.php.
store()
BristolSU\ControlDB\Http\Controllers\Api\Role\RoleController::store (StoreRoleRequest $request, RoleRepository $roleRepository, DataRoleRepository $dataRoleRepository)
Definition at line 24 of file RoleController.php.
update()
BristolSU\ControlDB\Http\Controllers\Api\Role\RoleController::update (Role $role, UpdateRoleRequest $request, RoleRepository $roleRepository, DataRoleRepository $dataRoleRepository)
Definition at line 34 of file RoleController.php.
References BristolSU\ControlDB\Contracts\Models\Role\data(), BristolSU\ControlDB\Contracts\Models\Role\setGroupId(), and BristolSU\ControlDB\Contracts\Models\Role\setPositionId().
The documentation for this class was generated from the following file:
src/Http/Controllers/Api/Role/RoleController.php