Bristol SU Control: BristolSU\ControlDB\Models\Tags\GroupTagCategory Class Reference
BristolSU\ControlDB\Models\Tags\GroupTagCategory Class Reference
Public Member Functions
id ()
name ()
description ()
reference ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory
tags ()
Static Protected Member Functions
static boot ()
Protected Attributes
$table = 'control_tag_categories'
$fillable
Detailed Description
Group Tag Category
Definition at line 13 of file GroupTagCategory.php.
Member Function Documentation
boot()
static BristolSU\ControlDB\Models\Tags\GroupTagCategory::boot () static protected
Boot the model
Add a scope to only retrieve group tag categories
Definition at line 22 of file GroupTagCategory.php.
description()
BristolSU\ControlDB\Models\Tags\GroupTagCategory::description ()
Deacription of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory.
Definition at line 72 of file GroupTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\GroupTagCategory\setDescription().
id()
BristolSU\ControlDB\Models\Tags\GroupTagCategory::id ()
ID of the tag category
Returns
mixed
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory.
Definition at line 52 of file GroupTagCategory.php.
name()
BristolSU\ControlDB\Models\Tags\GroupTagCategory::name ()
Name of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory.
Definition at line 62 of file GroupTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\GroupTagCategory\setName().
reference()
BristolSU\ControlDB\Models\Tags\GroupTagCategory::reference ()
Reference of the tag category
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory.
Definition at line 82 of file GroupTagCategory.php.
Referenced by BristolSU\ControlDB\Models\Tags\GroupTagCategory\setReference().
setDescription()
BristolSU\ControlDB\Models\Tags\GroupTagCategory::setDescription (string $description)
Set the description of the tag category
Parameters
string $description
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory.
Definition at line 103 of file GroupTagCategory.php.
References BristolSU\ControlDB\Models\Tags\GroupTagCategory\description().
setName()
BristolSU\ControlDB\Models\Tags\GroupTagCategory::setName (string $name)
Set the name of the tag category
Parameters
string $name
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory.
Definition at line 92 of file GroupTagCategory.php.
References BristolSU\ControlDB\Models\Tags\GroupTagCategory\name().
setReference()
BristolSU\ControlDB\Models\Tags\GroupTagCategory::setReference (string $reference)
Set the reference of the tag category
Parameters
string $reference
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTagCategory.
Definition at line 114 of file GroupTagCategory.php.
References BristolSU\ControlDB\Models\Tags\GroupTagCategory\reference().
Member Data Documentation
$fillable
BristolSU\ControlDB\Models\Tags\GroupTagCategory::$fillable protected
Initial value:
= [
        'name', 'description', 'reference'
    ]
Definition at line 43 of file GroupTagCategory.php.
$table
BristolSU\ControlDB\Models\Tags\GroupTagCategory::$table = 'control_tag_categories' protected
Definition at line 36 of file GroupTagCategory.php.
The documentation for this class was generated from the following file:
src/Models/Tags/GroupTagCategory.php