Bristol SU Control: BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagPositionController Class Reference
BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagPositionController Class Reference
Public Member Functions
index (PositionTag $positionTag)
update (PositionTag $positionTag, Position $position)
destroy (PositionTag $positionTag, Position $position)
Detailed Description
Handle the link between a position tag and a position
Definition at line 12 of file PositionTagPositionController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagPositionController::destroy (PositionTag $positionTag, Position $position)
Remove the position from the tag
Parameters
PositionTag $positionTag
Position $position
Definition at line 42 of file PositionTagPositionController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\removePosition().
index()
BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagPositionController::index (PositionTag $positionTag)
Get all positions with the given tag
Parameters
PositionTag $positionTag
Returns
Definition at line 20 of file PositionTagPositionController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\positions().
update()
BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagPositionController::update (PositionTag $positionTag, Position $position)
Add the position to the tag
Parameters
PositionTag $positionTag
Position $position
Definition at line 31 of file PositionTagPositionController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\addPosition().
The documentation for this class was generated from the following file:
src/Http/Controllers/PositionTag/PositionTagPositionController.php