Bristol SU Control: BristolSU\ControlDB\Repositories\Pivots\UserRole Class Reference
BristolSU\ControlDB\Repositories\Pivots\UserRole Class Reference
Public Member Functions
getUsersThroughRole (Role $role)
getRolesThroughUser (User $user)
addUserToRole (User $user, Role $role)
removeUserFromRole (User $user, Role $role)
Detailed Description
Handle the relationship between a role and a user
Definition at line 13 of file UserRole.php.
Member Function Documentation
addUserToRole()
BristolSU\ControlDB\Repositories\Pivots\UserRole::addUserToRole (User $user, Role $role)
Assign a user to a role
Parameters
User $user User to assign to the role
Role $role Role to assign the user to
Returns
void
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\UserRole.
Definition at line 57 of file UserRole.php.
References BristolSU\ControlDB\Contracts\Models\User\id(), and BristolSU\ControlDB\Contracts\Models\Role\id().
getRolesThroughUser()
BristolSU\ControlDB\Repositories\Pivots\UserRole::getRolesThroughUser (User $user)
Get all roles a user has
Parameters
User $user
Returns
Role[]|Collection Roles the given user is in
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\UserRole.
Definition at line 39 of file UserRole.php.
References BristolSU\ControlDB\Contracts\Models\User\id(), and BristolSU\ControlDB\Contracts\Models\Role\id().
getUsersThroughRole()
BristolSU\ControlDB\Repositories\Pivots\UserRole::getUsersThroughRole (Role $role)
Get all users who have a role
Parameters
Role $role
Returns
User[]|Collection Users who have the role
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\UserRole.
Definition at line 22 of file UserRole.php.
References BristolSU\ControlDB\Contracts\Models\Role\id(), and BristolSU\ControlDB\Contracts\Models\User\id().
removeUserFromRole()
BristolSU\ControlDB\Repositories\Pivots\UserRole::removeUserFromRole (User $user, Role $role)
Remove a user from a role
Parameters
User $user User to remove from the role
Role $role Role to remove the user from
Returns
void
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\UserRole.
Definition at line 70 of file UserRole.php.
References BristolSU\ControlDB\Contracts\Models\User\id(), and BristolSU\ControlDB\Contracts\Models\Role\id().
The documentation for this class was generated from the following file:
src/Repositories/Pivots/UserRole.php