Bristol SU Control: BristolSU\ControlDB\Export\FormattedItem Class Reference
BristolSU\ControlDB\Export\FormattedItem Class Reference
Public Member Functions
__construct ($original)
original ()
isType (string $type)
addRow ($key, $value)
getColumnNames ()
getItem ($column, $default=null)
preparedItems ()
toArray ()
toJson ($options=0)
__toString ()
Static Public Member Functions
static create ($original)
Private Attributes
$original
$prepared = []
Detailed Description
Definition at line 8 of file FormattedItem.php.
Constructor & Destructor Documentation
__construct()
BristolSU\ControlDB\Export\FormattedItem::__construct ($original)
Definition at line 25 of file FormattedItem.php.
References BristolSU\ControlDB\Export\FormattedItem\$original, and BristolSU\ControlDB\Export\FormattedItem\original().
Member Function Documentation
__toString()
BristolSU\ControlDB\Export\FormattedItem::__toString ()
Definition at line 85 of file FormattedItem.php.
References BristolSU\ControlDB\Export\FormattedItem\toJson().
addRow()
BristolSU\ControlDB\Export\FormattedItem::addRow ($key, $value)
Definition at line 46 of file FormattedItem.php.
Referenced by BristolSU\ControlDB\Export\Formatter\Group\SimpleGroupFormatter\formatItem(), BristolSU\ControlDB\Export\Formatter\User\SimpleUserFormatter\formatItem(), BristolSU\ControlDB\Export\Formatter\Role\SimpleRoleFormatter\formatItem(), BristolSU\ControlDB\Export\Formatter\Role\AddPositionInformationToRoles\formatItem(), and BristolSU\ControlDB\Export\Formatter\Role\AddGroupInformationToRoles\formatItem().
create()
static BristolSU\ControlDB\Export\FormattedItem::create ($original) static
Definition at line 30 of file FormattedItem.php.
References BristolSU\ControlDB\Export\FormattedItem\$original.
Referenced by BristolSU\ControlDB\Export\Handler\Handler\prepareItems().
getColumnNames()
BristolSU\ControlDB\Export\FormattedItem::getColumnNames ()
Definition at line 51 of file FormattedItem.php.
getItem()
BristolSU\ControlDB\Export\FormattedItem::getItem ($column, $default = null)
Definition at line 56 of file FormattedItem.php.
isType()
BristolSU\ControlDB\Export\FormattedItem::isType (string $type)
Definition at line 40 of file FormattedItem.php.
References BristolSU\ControlDB\Export\FormattedItem\original().
Referenced by BristolSU\ControlDB\Export\Formatter\Formatter\canHandle().
original()
BristolSU\ControlDB\Export\FormattedItem::original ()
Definition at line 35 of file FormattedItem.php.
References BristolSU\ControlDB\Export\FormattedItem\$original.
Referenced by BristolSU\ControlDB\Export\FormattedItem\__construct(), BristolSU\ControlDB\Export\Formatter\User\SimpleUserFormatter\formatItem(), BristolSU\ControlDB\Export\Formatter\Role\SimpleRoleFormatter\formatItem(), BristolSU\ControlDB\Export\Formatter\Role\AddPositionInformationToRoles\formatItem(), BristolSU\ControlDB\Export\Formatter\Role\AddGroupInformationToRoles\formatItem(), BristolSU\ControlDB\Export\Formatter\Group\SimpleGroupFormatter\formatItem(), and BristolSU\ControlDB\Export\FormattedItem\isType().
preparedItems()
BristolSU\ControlDB\Export\FormattedItem::preparedItems ()
Definition at line 64 of file FormattedItem.php.
References BristolSU\ControlDB\Export\FormattedItem\$prepared.
Referenced by BristolSU\ControlDB\Export\FormattedItem\toArray().
toArray()
BristolSU\ControlDB\Export\FormattedItem::toArray ()
Definition at line 72 of file FormattedItem.php.
References BristolSU\ControlDB\Export\FormattedItem\preparedItems().
Referenced by BristolSU\ControlDB\Export\FormattedItem\toJson().
toJson()
BristolSU\ControlDB\Export\FormattedItem::toJson ($options = 0)
Definition at line 80 of file FormattedItem.php.
References BristolSU\ControlDB\Export\FormattedItem\toArray().
Referenced by BristolSU\ControlDB\Export\FormattedItem\__toString().
Member Data Documentation
$original
BristolSU\ControlDB\Export\FormattedItem::$original private
Definition at line 16 of file FormattedItem.php.
Referenced by BristolSU\ControlDB\Export\FormattedItem\__construct(), BristolSU\ControlDB\Export\FormattedItem\create(), and BristolSU\ControlDB\Export\FormattedItem\original().
$prepared
BristolSU\ControlDB\Export\FormattedItem::$prepared = [] private
Definition at line 23 of file FormattedItem.php.
Referenced by BristolSU\ControlDB\Export\FormattedItem\preparedItems().
The documentation for this class was generated from the following file:
src/Export/FormattedItem.php