Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Api\Group\GroupUserController Class Reference
BristolSU\ControlDB\Http\Controllers\Api\Group\GroupUserController Class Reference
Public Member Functions
index (Group $group)
update (Group $group, User $user)
destroy (Group $group, User $user)
Detailed Description
Definition at line 9 of file GroupUserController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Api\Group\GroupUserController::destroy (Group $group, User $user)
Definition at line 22 of file GroupUserController.php.
References BristolSU\ControlDB\Contracts\Models\Group\removeUser().
index()
BristolSU\ControlDB\Http\Controllers\Api\Group\GroupUserController::index (Group $group)
Definition at line 12 of file GroupUserController.php.
References BristolSU\ControlDB\Contracts\Models\Group\members().
update()
BristolSU\ControlDB\Http\Controllers\Api\Group\GroupUserController::update (Group $group, User $user)
Definition at line 17 of file GroupUserController.php.
References BristolSU\ControlDB\Contracts\Models\Group\addUser().
The documentation for this class was generated from the following file:
src/Http/Controllers/Api/Group/GroupUserController.php