Bristol SU Control: BristolSU\ControlDB\Repositories\DataPosition Class Reference
BristolSU\ControlDB\Repositories\DataPosition Class Reference
Public Member Functions
getById (int $id)
getWhere ($attributes=[])
create (?string $name=null, ?string $description=null)
getAllWhere ($attributes=[])
Detailed Description
Definition at line 10 of file DataPosition.php.
Member Function Documentation
create()
BristolSU\ControlDB\Repositories\DataPosition::create (?string $name = null, ?string $description = null)
Create a new data position
Parameters
string | null $name
string | null $description
Returns
Implements BristolSU\ControlDB\Contracts\Repositories\DataPosition.
Definition at line 47 of file DataPosition.php.
getAllWhere()
BristolSU\ControlDB\Repositories\DataPosition::getAllWhere ($attributes = [])
Get all data positions where the given attributes match, including additional attributes.
Parameters
array $attributes
Returns
Collection
Implements BristolSU\ControlDB\Contracts\Repositories\DataPosition.
Definition at line 61 of file DataPosition.php.
References BristolSU\ControlDB\AdditionalProperties\ImplementsAdditionalProperties\getAdditionalAttributes().
Referenced by BristolSU\ControlDB\Repositories\DataPosition\getWhere().
getById()
BristolSU\ControlDB\Repositories\DataPosition::getById (int $id)
Get a data position by ID
Parameters
int $id
Returns
Implements BristolSU\ControlDB\Contracts\Repositories\DataPosition.
Definition at line 19 of file DataPosition.php.
getWhere()
BristolSU\ControlDB\Repositories\DataPosition::getWhere ($attributes = [])
Get a data position with the given attributes, including additional attributes.
Parameters
array $attributes
Returns
Implements BristolSU\ControlDB\Contracts\Repositories\DataPosition.
Definition at line 30 of file DataPosition.php.
References BristolSU\ControlDB\Repositories\DataPosition\getAllWhere().
The documentation for this class was generated from the following file:
src/Repositories/DataPosition.php