Bristol SU Control: BristolSU\ControlDB\Models\DataPosition Class Reference
BristolSU\ControlDB\Models\DataPosition Class Reference
Public Member Functions
id ()
name ()
description ()
setName (?string $name)
setDescription (?string $description)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\DataPosition
position ()
Public Member Functions inherited from BristolSU\ControlDB\AdditionalProperties\ImplementsAdditionalProperties
getAdditionalAttribute (string $key)
setAdditionalAttribute (string $key, $value)
Protected Attributes
$table = 'control_data_position'
$fillable
Additional Inherited Members
Static Public Member Functions inherited from BristolSU\ControlDB\AdditionalProperties\ImplementsAdditionalProperties
static addProperty (string $key)
Detailed Description
Handles attributes belonging to a position
Definition at line 15 of file DataPosition.php.
Member Function Documentation
description()
BristolSU\ControlDB\Models\DataPosition::description ()
Description for the position.
Returns
string|null
Implements BristolSU\ControlDB\Contracts\Models\DataPosition.
Definition at line 60 of file DataPosition.php.
Referenced by BristolSU\ControlDB\Models\DataPosition\setDescription().
id()
BristolSU\ControlDB\Models\DataPosition::id ()
ID of the position
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\DataPosition.
Definition at line 40 of file DataPosition.php.
name()
BristolSU\ControlDB\Models\DataPosition::name ()
Name of the position
Returns
string|null
Implements BristolSU\ControlDB\Contracts\Models\DataPosition.
Definition at line 50 of file DataPosition.php.
Referenced by BristolSU\ControlDB\Models\DataPosition\setName().
setDescription()
BristolSU\ControlDB\Models\DataPosition::setDescription (?string $description)
Set the description
Parameters
string | null $description
Implements BristolSU\ControlDB\Contracts\Models\DataPosition.
Definition at line 81 of file DataPosition.php.
References BristolSU\ControlDB\Models\DataPosition\description().
setName()
BristolSU\ControlDB\Models\DataPosition::setName (?string $name)
Set the position name
Parameters
string | null $name
Implements BristolSU\ControlDB\Contracts\Models\DataPosition.
Definition at line 70 of file DataPosition.php.
References BristolSU\ControlDB\Models\DataPosition\name().
Member Data Documentation
$fillable
BristolSU\ControlDB\Models\DataPosition::$fillable protected
Initial value:
= [
        'name', 'description'
    ]
Definition at line 31 of file DataPosition.php.
$table
BristolSU\ControlDB\Models\DataPosition::$table = 'control_data_position' protected
Definition at line 24 of file DataPosition.php.
The documentation for this class was generated from the following file:
src/Models/DataPosition.php