Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Api\User\UserGroupController Class Reference
BristolSU\ControlDB\Http\Controllers\Api\User\UserGroupController Class Reference
Public Member Functions
index (User $user)
update (User $user, Group $group)
destroy (User $user, Group $group)
Detailed Description
Definition at line 11 of file UserGroupController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Api\User\UserGroupController::destroy (User $user, Group $group)
Definition at line 24 of file UserGroupController.php.
References BristolSU\ControlDB\Contracts\Models\User\removeGroup().
index()
BristolSU\ControlDB\Http\Controllers\Api\User\UserGroupController::index (User $user)
Definition at line 14 of file UserGroupController.php.
References BristolSU\ControlDB\Contracts\Models\User\groups().
update()
BristolSU\ControlDB\Http\Controllers\Api\User\UserGroupController::update (User $user, Group $group)
Definition at line 19 of file UserGroupController.php.
References BristolSU\ControlDB\Contracts\Models\User\addGroup().
The documentation for this class was generated from the following file:
src/Http/Controllers/Api/User/UserGroupController.php