Bristol SU Control: BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag Class Reference
BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag Class Reference
Public Member Functions
addTagToUser (UserTag $userTag, User $user)
removeTagFromUser (UserTag $userTag, User $user)
getTagsThroughUser (User $user)
getUsersThroughTag (UserTag $userTag)
Detailed Description
Definition at line 11 of file UserUserTag.php.
Member Function Documentation
addTagToUser()
BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag::addTagToUser (UserTag $userTag, User $user)
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\UserUserTag.
Definition at line 17 of file UserUserTag.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\id(), and BristolSU\ControlDB\Contracts\Models\User\id().
getTagsThroughUser()
BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag::getTagsThroughUser (User $user)
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\UserUserTag.
Definition at line 37 of file UserUserTag.php.
References BristolSU\ControlDB\Contracts\Models\User\id(), and BristolSU\ControlDB\Contracts\Models\Tags\UserTag\id().
getUsersThroughTag()
BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag::getUsersThroughTag (UserTag $userTag)
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\UserUserTag.
Definition at line 52 of file UserUserTag.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\id(), and BristolSU\ControlDB\Contracts\Models\User\id().
removeTagFromUser()
BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag::removeTagFromUser (UserTag $userTag, User $user)
Implements BristolSU\ControlDB\Contracts\Repositories\Pivots\Tags\UserUserTag.
Definition at line 27 of file UserUserTag.php.
References BristolSU\ControlDB\Contracts\Models\Tags\UserTag\id(), and BristolSU\ControlDB\Contracts\Models\User\id().
The documentation for this class was generated from the following file:
src/Repositories/Pivots/Tags/UserUserTag.php