Bristol SU Control: BristolSU\ControlDB\ControlDBServiceProvider Class Reference
BristolSU\ControlDB\ControlDBServiceProvider Class Reference
Public Member Functions
register ()
boot ()
registerFactories ()
registerMigrations ()
bindContracts ()
registerCommands ()
setupRouteModelBinding ()
setupRoutes ()
Protected Member Functions
registerConfig ()
Detailed Description
Definition at line 92 of file ControlDBServiceProvider.php.
Member Function Documentation
bindContracts()
BristolSU\ControlDB\ControlDBServiceProvider::bindContracts ()
Definition at line 139 of file ControlDBServiceProvider.php.
Referenced by BristolSU\ControlDB\ControlDBServiceProvider\register().
boot()
BristolSU\ControlDB\ControlDBServiceProvider::boot ()
Definition at line 104 of file ControlDBServiceProvider.php.
References BristolSU\ControlDB\ControlDBServiceProvider\setupRouteModelBinding(), and BristolSU\ControlDB\ControlDBServiceProvider\setupRoutes().
register()
BristolSU\ControlDB\ControlDBServiceProvider::register ()
Definition at line 95 of file ControlDBServiceProvider.php.
References BristolSU\ControlDB\ControlDBServiceProvider\bindContracts(), BristolSU\ControlDB\ControlDBServiceProvider\registerCommands(), BristolSU\ControlDB\ControlDBServiceProvider\registerConfig(), BristolSU\ControlDB\ControlDBServiceProvider\registerFactories(), and BristolSU\ControlDB\ControlDBServiceProvider\registerMigrations().
registerCommands()
BristolSU\ControlDB\ControlDBServiceProvider::registerCommands ()
Definition at line 197 of file ControlDBServiceProvider.php.
Referenced by BristolSU\ControlDB\ControlDBServiceProvider\register().
registerConfig()
BristolSU\ControlDB\ControlDBServiceProvider::registerConfig () protected
Register config
Definition at line 113 of file ControlDBServiceProvider.php.
Referenced by BristolSU\ControlDB\ControlDBServiceProvider\register().
registerFactories()
BristolSU\ControlDB\ControlDBServiceProvider::registerFactories ()
Register factories in a non-production environment
Exceptions
BindingResolutionException
Definition at line 127 of file ControlDBServiceProvider.php.
Referenced by BristolSU\ControlDB\ControlDBServiceProvider\register().
registerMigrations()
BristolSU\ControlDB\ControlDBServiceProvider::registerMigrations ()
Definition at line 134 of file ControlDBServiceProvider.php.
Referenced by BristolSU\ControlDB\ControlDBServiceProvider\register().
setupRouteModelBinding()
BristolSU\ControlDB\ControlDBServiceProvider::setupRouteModelBinding ()
Definition at line 204 of file ControlDBServiceProvider.php.
Referenced by BristolSU\ControlDB\ControlDBServiceProvider\boot().
setupRoutes()
BristolSU\ControlDB\ControlDBServiceProvider::setupRoutes ()
Definition at line 259 of file ControlDBServiceProvider.php.
Referenced by BristolSU\ControlDB\ControlDBServiceProvider\boot().
The documentation for this class was generated from the following file:
src/ControlDBServiceProvider.php