Bristol SU Control: BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagController Class Reference
BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagController Class Reference
Public Member Functions
index (PositionTagRepository $positionTagRepository)
show (PositionTag $positionTag)
store (PositionTagStoreRequest $request, PositionTagRepository $positionTagRepository)
update (PositionTag $positionTag, PositionTagUpdateRequest $request)
destroy (PositionTag $positionTag, PositionTagRepository $positionTagRepository)
Public Member Functions inherited from BristolSU\ControlDB\Http\Controllers\Controller
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Handle position tags
Definition at line 14 of file PositionTagController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagController::destroy (PositionTag $positionTag, PositionTagRepository $positionTagRepository)
Delete a position tag
Parameters
PositionTag $positionTag
PositionTagRepository $positionTagRepository
Definition at line 87 of file PositionTagController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\id().
index()
BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagController::index (PositionTagRepository $positionTagRepository)
Get all position tags
Parameters
PositionTagRepository $positionTagRepository
Returns
Definition at line 23 of file PositionTagController.php.
References BristolSU\ControlDB\Http\Controllers\Controller\paginate().
show()
BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagController::show (PositionTag $positionTag)
Show information about a single position tag
Parameters
PositionTag $positionTag
Returns
PositionTag
Definition at line 34 of file PositionTagController.php.
store()
BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagController::store (PositionTagStoreRequest $request, PositionTagRepository $positionTagRepository)
Create a new position tag
Parameters
PositionTagStoreRequest $request
PositionTagRepository $positionTagRepository
Returns
PositionTag
Definition at line 46 of file PositionTagController.php.
update()
BristolSU\ControlDB\Http\Controllers\PositionTag\PositionTagController::update (PositionTag $positionTag, PositionTagUpdateRequest $request)
Update a position tag
Parameters
PositionTag $positionTag
PositionTagUpdateRequest $request
Returns
PositionTag
Definition at line 63 of file PositionTagController.php.
References BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\setDescription(), BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\setName(), BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\setReference(), and BristolSU\ControlDB\Contracts\Models\Tags\PositionTag\setTagCategoryId().
The documentation for this class was generated from the following file:
src/Http/Controllers/PositionTag/PositionTagController.php