Bristol SU Control: BristolSU\ControlDB\Http\Controllers\User\UserUserTagController Class Reference
BristolSU\ControlDB\Http\Controllers\User\UserUserTagController Class Reference
Public Member Functions
index (User $user)
update (User $user, UserTag $userTag)
destroy (User $user, UserTag $userTag)
Public Member Functions inherited from BristolSU\ControlDB\Http\Controllers\Controller
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Handle the tagging and untagging of users
Definition at line 12 of file UserUserTagController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\User\UserUserTagController::destroy (User $user, UserTag $userTag)
Untag user
Parameters
User $user
UserTag $userTag
Definition at line 44 of file UserUserTagController.php.
References BristolSU\ControlDB\Contracts\Models\User\removeTag().
index()
BristolSU\ControlDB\Http\Controllers\User\UserUserTagController::index (User $user)
Get all tags belonging to the current user
Parameters
User $user
Returns
Definition at line 21 of file UserUserTagController.php.
References BristolSU\ControlDB\Http\Controllers\Controller\paginate(), and BristolSU\ControlDB\Contracts\Models\User\tags().
update()
BristolSU\ControlDB\Http\Controllers\User\UserUserTagController::update (User $user, UserTag $userTag)
Tag a user
Parameters
User $user
UserTag $userTag
Definition at line 33 of file UserUserTagController.php.
References BristolSU\ControlDB\Contracts\Models\User\addTag().
The documentation for this class was generated from the following file:
src/Http/Controllers/User/UserUserTagController.php