Bristol SU Control: BristolSU\ControlDB\Models\DataUser Class Reference
BristolSU\ControlDB\Models\DataUser Class Reference
Public Member Functions
id ()
firstName ()
lastName ()
email ()
dob ()
preferredName ()
setFirstName (?string $firstName)
setLastName (?string $lastName)
setEmail (?string $email)
setDob (?DateTime $dob)
setPreferredName (?string $name)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\DataUser
user ()
Public Member Functions inherited from BristolSU\ControlDB\AdditionalProperties\ImplementsAdditionalProperties
getAdditionalAttribute (string $key)
setAdditionalAttribute (string $key, $value)
saveAdditionalAttribute (string $key, $value)
Protected Attributes
$table = 'control_data_user'
$fillable
$casts
Additional Inherited Members
Static Public Member Functions inherited from BristolSU\ControlDB\AdditionalProperties\ImplementsAdditionalProperties
static addProperty (string $key)
static getAdditionalAttributes ()
Detailed Description
Handles attributes belonging to a user
Definition at line 16 of file DataUser.php.
Member Function Documentation
dob()
BristolSU\ControlDB\Models\DataUser::dob ()
Get the date of birth for the user
Returns
DateTime|null
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 90 of file DataUser.php.
Referenced by BristolSU\ControlDB\Models\DataUser\setDob().
email()
BristolSU\ControlDB\Models\DataUser::email ()
Get the email for the user
Returns
string|null
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 80 of file DataUser.php.
Referenced by BristolSU\ControlDB\Models\DataUser\setEmail().
firstName()
BristolSU\ControlDB\Models\DataUser::firstName ()
Get the first name for the user
Returns
string|null
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 60 of file DataUser.php.
id()
BristolSU\ControlDB\Models\DataUser::id ()
Get the ID of the user
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 50 of file DataUser.php.
lastName()
BristolSU\ControlDB\Models\DataUser::lastName ()
Get the last name for the user
Returns
string|null
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 70 of file DataUser.php.
preferredName()
BristolSU\ControlDB\Models\DataUser::preferredName ()
Get the preferred name for the user
Returns
string|null
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 100 of file DataUser.php.
setDob()
BristolSU\ControlDB\Models\DataUser::setDob (?DateTime $dob)
Set the date of birth attribute
Parameters
DateTime | null $dob
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 143 of file DataUser.php.
References BristolSU\ControlDB\Models\DataUser\dob().
setEmail()
BristolSU\ControlDB\Models\DataUser::setEmail (?string $email)
Set the users email
Parameters
string | null $email
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 132 of file DataUser.php.
References BristolSU\ControlDB\Models\DataUser\email().
setFirstName()
BristolSU\ControlDB\Models\DataUser::setFirstName (?string $firstName)
Set the users first name
Parameters
string | null $firstName
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 110 of file DataUser.php.
setLastName()
BristolSU\ControlDB\Models\DataUser::setLastName (?string $lastName)
Set the users last name
Parameters
string | null $lastName
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 121 of file DataUser.php.
setPreferredName()
BristolSU\ControlDB\Models\DataUser::setPreferredName (?string $name)
Set the preferred name for the user
Parameters
string | null $name
Implements BristolSU\ControlDB\Contracts\Models\DataUser.
Definition at line 154 of file DataUser.php.
Member Data Documentation
$casts
BristolSU\ControlDB\Models\DataUser::$casts protected
Initial value:
= [
        'dob' => 'date:d-m-Y'
    ]
Definition at line 41 of file DataUser.php.
$fillable
BristolSU\ControlDB\Models\DataUser::$fillable protected
Initial value:
= [
        'first_name', 'last_name', 'email', 'dob', 'preferred_name'
    ]
Definition at line 32 of file DataUser.php.
$table
BristolSU\ControlDB\Models\DataUser::$table = 'control_data_user' protected
Definition at line 25 of file DataUser.php.
The documentation for this class was generated from the following file:
src/Models/DataUser.php