Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Role\RoleUserController Class Reference
BristolSU\ControlDB\Http\Controllers\Role\RoleUserController Class Reference
Public Member Functions
index (Role $role)
update (Role $role, User $user)
destroy (Role $role, User $user)
Detailed Description
Handles the link between a role and a user
Definition at line 14 of file RoleUserController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Role\RoleUserController::destroy (Role $role, User $user)
Remove a user from a role
Parameters
Role $role
User $user
Definition at line 45 of file RoleUserController.php.
References BristolSU\ControlDB\Contracts\Models\Role\removeUser().
index()
BristolSU\ControlDB\Http\Controllers\Role\RoleUserController::index (Role $role)
Get all users belonging to a group
Parameters
Role $role
Returns
Definition at line 23 of file RoleUserController.php.
References BristolSU\ControlDB\Contracts\Models\Role\users().
update()
BristolSU\ControlDB\Http\Controllers\Role\RoleUserController::update (Role $role, User $user)
Add a user to a role
Parameters
Role $role
User $user
Definition at line 34 of file RoleUserController.php.
References BristolSU\ControlDB\Contracts\Models\Role\addUser().
The documentation for this class was generated from the following file:
src/Http/Controllers/Role/RoleUserController.php