Bristol SU Control: BristolSU\ControlDB\Models\Tags\GroupTag Class Reference
BristolSU\ControlDB\Models\Tags\GroupTag Class Reference
Public Member Functions
id ()
name ()
description ()
reference ()
categoryId ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
setTagCategoryId ($categoryId)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\Tags\GroupTag
category ()
fullReference ()
groups ()
setTagCategoryId (int $categoryId)
addGroup (Group $group)
removeGroup (Group $group)
Static Protected Member Functions
static boot ()
Protected Attributes
$table = 'control_tags'
$fillable
Detailed Description
Class GroupTag
Definition at line 13 of file GroupTag.php.
Member Function Documentation
boot()
static BristolSU\ControlDB\Models\Tags\GroupTag::boot () static protected
Boot the model
Add a global scope to only return group tags
Definition at line 22 of file GroupTag.php.
categoryId()
BristolSU\ControlDB\Models\Tags\GroupTag::categoryId ()
ID of the tag category
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTag.
Definition at line 90 of file GroupTag.php.
description()
BristolSU\ControlDB\Models\Tags\GroupTag::description ()
Description of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTag.
Definition at line 70 of file GroupTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\GroupTag\setDescription().
id()
BristolSU\ControlDB\Models\Tags\GroupTag::id ()
ID of the group tag
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTag.
Definition at line 50 of file GroupTag.php.
name()
BristolSU\ControlDB\Models\Tags\GroupTag::name ()
Name of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTag.
Definition at line 60 of file GroupTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\GroupTag\setName().
reference()
BristolSU\ControlDB\Models\Tags\GroupTag::reference ()
Reference of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTag.
Definition at line 80 of file GroupTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\GroupTag\setReference().
setDescription()
BristolSU\ControlDB\Models\Tags\GroupTag::setDescription (string $description)
Set the description of the tagTag Reference
Parameters
string $description
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTag.
Definition at line 111 of file GroupTag.php.
References BristolSU\ControlDB\Models\Tags\GroupTag\description().
setName()
BristolSU\ControlDB\Models\Tags\GroupTag::setName (string $name)
Set the name of the tag
Parameters
string $name
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTag.
Definition at line 100 of file GroupTag.php.
References BristolSU\ControlDB\Models\Tags\GroupTag\name().
setReference()
BristolSU\ControlDB\Models\Tags\GroupTag::setReference (string $reference)
Set the reference of the tag
Parameters
string $reference
Implements BristolSU\ControlDB\Contracts\Models\Tags\GroupTag.
Definition at line 122 of file GroupTag.php.
References BristolSU\ControlDB\Models\Tags\GroupTag\reference().
setTagCategoryId()
BristolSU\ControlDB\Models\Tags\GroupTag::setTagCategoryId ($categoryId)
Set the tag category ID
Parameters
int $categoryId
Definition at line 133 of file GroupTag.php.
Member Data Documentation
$fillable
BristolSU\ControlDB\Models\Tags\GroupTag::$fillable protected
Initial value:
= [
        'name', 'description', 'reference', 'tag_category_id'
    ]
Definition at line 40 of file GroupTag.php.
$table
BristolSU\ControlDB\Models\Tags\GroupTag::$table = 'control_tags' protected
Definition at line 33 of file GroupTag.php.
The documentation for this class was generated from the following file:
src/Models/Tags/GroupTag.php