Bristol SU Control: BristolSU\ControlDB\Models\Tags\RoleTag Class Reference
BristolSU\ControlDB\Models\Tags\RoleTag Class Reference
Public Member Functions
id ()
name ()
description ()
reference ()
categoryId ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
setTagCategoryId ($categoryId)
Public Member Functions inherited from BristolSU\ControlDB\Contracts\Models\Tags\RoleTag
category ()
fullReference ()
roles ()
setTagCategoryId (int $categoryId)
addRole (Role $role)
removeRole (Role $role)
Static Protected Member Functions
static boot ()
Protected Attributes
$table = 'control_tags'
$fillable
Detailed Description
Class RoleTag
Definition at line 13 of file RoleTag.php.
Member Function Documentation
boot()
static BristolSU\ControlDB\Models\Tags\RoleTag::boot () static protected
Boot the model
Add a global scope to only return role tags
Definition at line 22 of file RoleTag.php.
categoryId()
BristolSU\ControlDB\Models\Tags\RoleTag::categoryId ()
ID of the tag category
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTag.
Definition at line 90 of file RoleTag.php.
description()
BristolSU\ControlDB\Models\Tags\RoleTag::description ()
Description of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTag.
Definition at line 70 of file RoleTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\RoleTag\setDescription().
id()
BristolSU\ControlDB\Models\Tags\RoleTag::id ()
ID of the role tag
Returns
int
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTag.
Definition at line 50 of file RoleTag.php.
name()
BristolSU\ControlDB\Models\Tags\RoleTag::name ()
Name of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTag.
Definition at line 60 of file RoleTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\RoleTag\setName().
reference()
BristolSU\ControlDB\Models\Tags\RoleTag::reference ()
Reference of the tag
Returns
string
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTag.
Definition at line 80 of file RoleTag.php.
Referenced by BristolSU\ControlDB\Models\Tags\RoleTag\setReference().
setDescription()
BristolSU\ControlDB\Models\Tags\RoleTag::setDescription (string $description)
Set the description of the tagTag Reference
Parameters
string $description
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTag.
Definition at line 111 of file RoleTag.php.
References BristolSU\ControlDB\Models\Tags\RoleTag\description().
setName()
BristolSU\ControlDB\Models\Tags\RoleTag::setName (string $name)
Set the name of the tag
Parameters
string $name
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTag.
Definition at line 100 of file RoleTag.php.
References BristolSU\ControlDB\Models\Tags\RoleTag\name().
setReference()
BristolSU\ControlDB\Models\Tags\RoleTag::setReference (string $reference)
Set the reference of the tag
Parameters
string $reference
Implements BristolSU\ControlDB\Contracts\Models\Tags\RoleTag.
Definition at line 122 of file RoleTag.php.
References BristolSU\ControlDB\Models\Tags\RoleTag\reference().
setTagCategoryId()
BristolSU\ControlDB\Models\Tags\RoleTag::setTagCategoryId ($categoryId)
Set the tag category ID
Parameters
int $categoryId
Definition at line 133 of file RoleTag.php.
Member Data Documentation
$fillable
BristolSU\ControlDB\Models\Tags\RoleTag::$fillable protected
Initial value:
= [
        'name', 'description', 'reference', 'tag_category_id'
    ]
Definition at line 40 of file RoleTag.php.
$table
BristolSU\ControlDB\Models\Tags\RoleTag::$table = 'control_tags' protected
Definition at line 33 of file RoleTag.php.
The documentation for this class was generated from the following file:
src/Models/Tags/RoleTag.php