Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Group\GroupUserController Class Reference
BristolSU\ControlDB\Http\Controllers\Group\GroupUserController Class Reference
Public Member Functions
index (Group $group)
update (Group $group, User $user)
destroy (Group $group, User $user)
Public Member Functions inherited from BristolSU\ControlDB\Http\Controllers\Controller
paginate ($items)
paginationResponse ($items, $count)
Detailed Description
Handles the link between a group and a user
Definition at line 12 of file GroupUserController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Group\GroupUserController::destroy (Group $group, User $user)
Remove a user from a group
Parameters
Group $group
User $user
Definition at line 43 of file GroupUserController.php.
References BristolSU\ControlDB\Contracts\Models\Group\removeUser().
index()
BristolSU\ControlDB\Http\Controllers\Group\GroupUserController::index (Group $group)
Get all users from a group
Parameters
Group $group
Returns
Definition at line 21 of file GroupUserController.php.
References BristolSU\ControlDB\Contracts\Models\Group\members(), and BristolSU\ControlDB\Http\Controllers\Controller\paginate().
update()
BristolSU\ControlDB\Http\Controllers\Group\GroupUserController::update (Group $group, User $user)
Add a user to a group
Parameters
Group $group
User $user
Definition at line 32 of file GroupUserController.php.
References BristolSU\ControlDB\Contracts\Models\Group\addUser().
The documentation for this class was generated from the following file:
src/Http/Controllers/Group/GroupUserController.php