Bristol SU Control: BristolSU\ControlDB\Http\Controllers\Api\Position\PositionTagController Class Reference
BristolSU\ControlDB\Http\Controllers\Api\Position\PositionTagController Class Reference
Public Member Functions
index (Position $position)
update (Position $position, PositionTag $positionTag)
destroy (Position $position, PositionTag $positionTag)
Detailed Description
Definition at line 9 of file PositionTagController.php.
Member Function Documentation
destroy()
BristolSU\ControlDB\Http\Controllers\Api\Position\PositionTagController::destroy (Position $position, PositionTag $positionTag)
Definition at line 22 of file PositionTagController.php.
References BristolSU\ControlDB\Contracts\Models\Position\removeTag().
index()
BristolSU\ControlDB\Http\Controllers\Api\Position\PositionTagController::index (Position $position)
Definition at line 12 of file PositionTagController.php.
References BristolSU\ControlDB\Contracts\Models\Position\tags().
update()
BristolSU\ControlDB\Http\Controllers\Api\Position\PositionTagController::update (Position $position, PositionTag $positionTag)
Definition at line 17 of file PositionTagController.php.
References BristolSU\ControlDB\Contracts\Models\Position\addTag().
The documentation for this class was generated from the following file:
src/Http/Controllers/Api/Position/PositionTagController.php