Bristol SU Control: BristolSU\ControlDB\Contracts\Models\Tags\GroupTag Interface Reference
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag Interface Reference
Public Member Functions
id ()
name ()
description ()
reference ()
categoryId ()
category ()
fullReference ()
groups ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
setTagCategoryId (int $categoryId)
addGroup (Group $group)
removeGroup (Group $group)
Detailed Description
Represents a Group Tag
Definition at line 15 of file GroupTag.php.
Member Function Documentation
addGroup()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::addGroup (Group $group)
Add a group to the tag
Parameters
Group $group
Referenced by BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagGroupController\update().
category()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::category ()
Tag Category
Returns
GroupTagCategory
Referenced by BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagGroupTagCategoryController\index().
categoryId()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::categoryId ()
ID of the tag category
Returns
int
Implemented in BristolSU\ControlDB\Models\Tags\GroupTag.
description()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::description ()
Description of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\GroupTag.
fullReference()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::fullReference ()
Full reference of the tag
This should be the tag category reference and the tag reference, separated with a period.
Returns
string
groups()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::groups ()
Groups who have this tag
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagGroupController\index().
id()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::id ()
ID of the group tag
Returns
int
Implemented in BristolSU\ControlDB\Models\Tags\GroupTag.
Referenced by BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag\addTagToGroup(), BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController\destroy(), BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag\getGroupsThroughTag(), BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag\getTagsThroughGroup(), and BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag\removeTagFromGroup().
name()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::name ()
Name of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\GroupTag.
reference()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::reference ()
Reference of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\GroupTag.
removeGroup()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::removeGroup (Group $group)
Remove a group from the tag
Parameters
Group $group
Referenced by BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagGroupController\destroy().
setDescription()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::setDescription (string $description)
Set the description of the tag
Parameters
string $description
Implemented in BristolSU\ControlDB\Models\Tags\GroupTag.
Referenced by BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController\update().
setName()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::setName (string $name)
Set the name of the tag
Parameters
string $name
Implemented in BristolSU\ControlDB\Models\Tags\GroupTag.
Referenced by BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController\update().
setReference()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::setReference (string $reference)
Set the reference of the tag
Parameters
string $reference
Implemented in BristolSU\ControlDB\Models\Tags\GroupTag.
Referenced by BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController\update().
setTagCategoryId()
BristolSU\ControlDB\Contracts\Models\Tags\GroupTag::setTagCategoryId (int $categoryId)
Set the tag category ID
Parameters
int $categoryId
Referenced by BristolSU\ControlDB\Http\Controllers\GroupTag\GroupTagController\update().
The documentation for this interface was generated from the following file:
src/Contracts/Models/Tags/GroupTag.php