Bristol SU Control: BristolSU\ControlDB\Contracts\Models\User Interface Reference
BristolSU\ControlDB\Contracts\Models\User Interface Reference
Public Member Functions
id ()
dataProviderId ()
setDataProviderId (int $dataProviderId)
data ()
tags ()
roles ()
groups ()
addTag (UserTag $userTag)
removeTag (UserTag $userTag)
addRole (Role $role)
removeRole (Role $role)
addGroup (Group $group)
removeGroup (Group $group)
Detailed Description
Interface User
Definition at line 15 of file User.php.
Member Function Documentation
addGroup()
BristolSU\ControlDB\Contracts\Models\User::addGroup (Group $group)
Add a group from the user
Parameters
Group $group
Referenced by BristolSU\ControlDB\Http\Controllers\Api\User\UserGroupController\update().
addRole()
BristolSU\ControlDB\Contracts\Models\User::addRole (Role $role)
Add a role to the user
Parameters
Role $role
Referenced by BristolSU\ControlDB\Http\Controllers\Api\User\UserRoleController\update().
addTag()
BristolSU\ControlDB\Contracts\Models\User::addTag (UserTag $userTag)
Add a tag to the user
Parameters
UserTag $userTag
Referenced by BristolSU\ControlDB\Http\Controllers\Api\User\UserUserTagController\update().
data()
BristolSU\ControlDB\Contracts\Models\User::data ()
Get the data attributes for the user
Returns
DataUser
Referenced by BristolSU\ControlDB\Http\Controllers\Api\User\UserController\update().
dataProviderId()
BristolSU\ControlDB\Contracts\Models\User::dataProviderId ()
ID of the data provider for the user
Returns
int
groups()
BristolSU\ControlDB\Contracts\Models\User::groups ()
Groups the user is a member of
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\Api\User\UserGroupController\index().
id()
BristolSU\ControlDB\Contracts\Models\User::id ()
ID of the user
Returns
mixed
Referenced by BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag\addTagToUser(), BristolSU\ControlDB\Repositories\Pivots\UserGroup\addUserToGroup(), BristolSU\ControlDB\Repositories\Pivots\UserRole\addUserToRole(), BristolSU\ControlDB\Http\Controllers\Api\User\UserController\destroy(), BristolSU\ControlDB\Repositories\Pivots\UserGroup\getGroupsThroughUser(), BristolSU\ControlDB\Repositories\Pivots\UserRole\getRolesThroughUser(), BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag\getTagsThroughUser(), BristolSU\ControlDB\Repositories\Pivots\UserGroup\getUsersThroughGroup(), BristolSU\ControlDB\Repositories\Pivots\UserRole\getUsersThroughRole(), BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag\getUsersThroughTag(), BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag\removeTagFromUser(), BristolSU\ControlDB\Repositories\Pivots\UserGroup\removeUserFromGroup(), and BristolSU\ControlDB\Repositories\Pivots\UserRole\removeUserFromRole().
removeGroup()
BristolSU\ControlDB\Contracts\Models\User::removeGroup (Group $group)
Remove a group from the user
Parameters
Group $group
Referenced by BristolSU\ControlDB\Http\Controllers\Api\User\UserGroupController\destroy().
removeRole()
BristolSU\ControlDB\Contracts\Models\User::removeRole (Role $role)
Remove a role from the user
Parameters
Role $role
Referenced by BristolSU\ControlDB\Http\Controllers\Api\User\UserRoleController\destroy().
removeTag()
BristolSU\ControlDB\Contracts\Models\User::removeTag (UserTag $userTag)
Remove a tag from the user
Parameters
UserTag $userTag
Referenced by BristolSU\ControlDB\Http\Controllers\Api\User\UserUserTagController\destroy().
roles()
BristolSU\ControlDB\Contracts\Models\User::roles ()
Roles the user owns
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\Api\User\UserRoleController\index().
setDataProviderId()
BristolSU\ControlDB\Contracts\Models\User::setDataProviderId (int $dataProviderId)
Set data provider of the user
Parameters
int $dataProviderId
tags()
BristolSU\ControlDB\Contracts\Models\User::tags ()
Tags the user is tagged with
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\Api\User\UserUserTagController\index().
The documentation for this interface was generated from the following file:
src/Contracts/Models/User.php