Bristol SU Control: BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory Interface Reference
BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory Interface Reference
Public Member Functions
id ()
name ()
description ()
reference ()
tags ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
Detailed Description
Represents a position tag category
Definition at line 12 of file PositionTagCategory.php.
Member Function Documentation
description()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory::description ()
Deacription of the tag category
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\PositionTagCategory.
id()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory::id ()
ID of the tag category
Returns
mixed
Implemented in BristolSU\ControlDB\Models\Tags\PositionTagCategory.
Referenced by BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController\destroy().
name()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory::name ()
Name of the tag category
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\PositionTagCategory.
reference()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory::reference ()
Reference of the tag category
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\PositionTagCategory.
setDescription()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory::setDescription (string $description)
Set a description for the position tag category
Parameters
string $description
Implemented in BristolSU\ControlDB\Models\Tags\PositionTagCategory.
Referenced by BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController\update().
setName()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory::setName (string $name)
Set the name of the position tag category
Parameters
string $name
Implemented in BristolSU\ControlDB\Models\Tags\PositionTagCategory.
Referenced by BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController\update().
setReference()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory::setReference (string $reference)
Set a reference for a position tag category
Parameters
string $reference
Implemented in BristolSU\ControlDB\Models\Tags\PositionTagCategory.
Referenced by BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryController\update().
tags()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTagCategory::tags ()
All tags under this tag category
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\PositionTagCategory\PositionTagCategoryPositionTagController\index().
The documentation for this interface was generated from the following file:
src/Contracts/Models/Tags/PositionTagCategory.php