Bristol SU Control: BristolSU\ControlDB\Contracts\Models\Tags\PositionTag Interface Reference
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag Interface Reference
Public Member Functions
id ()
name ()
description ()
reference ()
categoryId ()
category ()
fullReference ()
positions ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
setTagCategoryId (int $categoryId)
addPosition (Position $position)
removePosition (Position $position)
Detailed Description
Represents a Position Tag
Definition at line 15 of file PositionTag.php.
Member Function Documentation
addPosition()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::addPosition (Position $position)
Add a position to the tag
Parameters
Position $position
category()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::category ()
Tag Category
Returns
PositionTagCategory
categoryId()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::categoryId ()
ID of the tag category
Returns
int
Implemented in BristolSU\ControlDB\Models\Tags\PositionTag.
description()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::description ()
Description of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\PositionTag.
fullReference()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::fullReference ()
Full reference of the tag
This should be the tag category reference and the tag reference, separated with a period.
Returns
string
id()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::id ()
ID of the position tag
Returns
int
Implemented in BristolSU\ControlDB\Models\Tags\PositionTag.
Referenced by BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag\addTagToPosition(), BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag\getPositionsThroughTag(), BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag\getTagsThroughPosition(), and BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag\removeTagFromPosition().
name()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::name ()
Name of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\PositionTag.
positions()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::positions ()
Positions who have this tag
Returns
Collection
reference()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::reference ()
Reference of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\PositionTag.
removePosition()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::removePosition (Position $position)
Remove a position from the tag
Parameters
Position $position
setDescription()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::setDescription (string $description)
Set the description of the tag
Parameters
string $description
Implemented in BristolSU\ControlDB\Models\Tags\PositionTag.
setName()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::setName (string $name)
Set the name of the tag
Parameters
string $name
Implemented in BristolSU\ControlDB\Models\Tags\PositionTag.
setReference()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::setReference (string $reference)
Set the reference of the tag
Parameters
string $reference
Implemented in BristolSU\ControlDB\Models\Tags\PositionTag.
setTagCategoryId()
BristolSU\ControlDB\Contracts\Models\Tags\PositionTag::setTagCategoryId (int $categoryId)
Set the tag category ID
Parameters
int $categoryId
The documentation for this interface was generated from the following file:
src/Contracts/Models/Tags/PositionTag.php