Bristol SU Control: BristolSU\ControlDB\Contracts\Models\Role Interface Reference
BristolSU\ControlDB\Contracts\Models\Role Interface Reference
Public Member Functions
id ()
positionId ()
dataProviderId ()
groupId ()
setGroupId (int $groupId)
setPositionId (int $positionId)
setDataProviderId (int $dataProviderId)
data ()
position ()
group ()
users ()
tags ()
addTag (RoleTag $roleTag)
removeTag (RoleTag $roleTag)
addUser (User $user)
removeUser (User $user)
Detailed Description
Represents a role
Definition at line 15 of file Role.php.
Member Function Documentation
addTag()
BristolSU\ControlDB\Contracts\Models\Role::addTag (RoleTag $roleTag)
Add a tag to the role
Parameters
RoleTag $roleTag
Referenced by BristolSU\ControlDB\Http\Controllers\Role\RoleRoleTagController\update().
addUser()
BristolSU\ControlDB\Contracts\Models\Role::addUser (User $user)
Add a user to the role
Parameters
User $user
Referenced by BristolSU\ControlDB\Http\Controllers\Role\RoleUserController\update().
data()
BristolSU\ControlDB\Contracts\Models\Role::data ()
Data associated with the role
Returns
DataRole
Referenced by BristolSU\ControlDB\Models\Role\getDataAttribute(), and BristolSU\ControlDB\Http\Controllers\Role\RoleController\update().
dataProviderId()
BristolSU\ControlDB\Contracts\Models\Role::dataProviderId ()
ID of the role data provider
Returns
int
Implemented in BristolSU\ControlDB\Models\Role.
group()
BristolSU\ControlDB\Contracts\Models\Role::group ()
Group belonging to the role
Returns
Group
Referenced by BristolSU\ControlDB\Http\Controllers\Role\RoleGroupController\index().
groupId()
BristolSU\ControlDB\Contracts\Models\Role::groupId ()
ID of the group
Returns
mixed
Implemented in BristolSU\ControlDB\Models\Role.
id()
BristolSU\ControlDB\Contracts\Models\Role::id ()
Get the ID of the role
Returns
int
Implemented in BristolSU\ControlDB\Models\Role.
Referenced by BristolSU\ControlDB\Repositories\Pivots\Tags\RoleRoleTag\addTagToRole(), BristolSU\ControlDB\Repositories\Pivots\UserRole\addUserToRole(), BristolSU\ControlDB\Http\Controllers\Role\RoleController\destroy(), BristolSU\ControlDB\Repositories\Pivots\Tags\RoleRoleTag\getRolesThroughTag(), BristolSU\ControlDB\Repositories\Pivots\UserRole\getRolesThroughUser(), BristolSU\ControlDB\Repositories\Pivots\Tags\RoleRoleTag\getTagsThroughRole(), BristolSU\ControlDB\Repositories\Pivots\UserRole\getUsersThroughRole(), BristolSU\ControlDB\Repositories\Pivots\Tags\RoleRoleTag\removeTagFromRole(), and BristolSU\ControlDB\Repositories\Pivots\UserRole\removeUserFromRole().
position()
BristolSU\ControlDB\Contracts\Models\Role::position ()
Position belonging to the role
Returns
Position
Referenced by BristolSU\ControlDB\Http\Controllers\Role\RolePositionController\index().
positionId()
BristolSU\ControlDB\Contracts\Models\Role::positionId ()
ID of the position the role belongs to
Returns
mixed
Implemented in BristolSU\ControlDB\Models\Role.
removeTag()
BristolSU\ControlDB\Contracts\Models\Role::removeTag (RoleTag $roleTag)
Remove a tag from the role
Parameters
RoleTag $roleTag
Referenced by BristolSU\ControlDB\Http\Controllers\Role\RoleRoleTagController\destroy().
removeUser()
BristolSU\ControlDB\Contracts\Models\Role::removeUser (User $user)
Remove a user from the role
Parameters
User $user
Referenced by BristolSU\ControlDB\Http\Controllers\Role\RoleUserController\destroy().
setDataProviderId()
BristolSU\ControlDB\Contracts\Models\Role::setDataProviderId (int $dataProviderId)
Set the ID of the data provider
Parameters
int $dataProviderId
Implemented in BristolSU\ControlDB\Models\Role.
setGroupId()
BristolSU\ControlDB\Contracts\Models\Role::setGroupId (int $groupId)
Set the ID of the group the role belongs to
Parameters
int $groupId
Implemented in BristolSU\ControlDB\Models\Role.
Referenced by BristolSU\ControlDB\Http\Controllers\Role\RoleController\update().
setPositionId()
BristolSU\ControlDB\Contracts\Models\Role::setPositionId (int $positionId)
Set the ID of the position the group belongs to
Parameters
int $positionId
Implemented in BristolSU\ControlDB\Models\Role.
Referenced by BristolSU\ControlDB\Http\Controllers\Role\RoleController\update().
tags()
BristolSU\ControlDB\Contracts\Models\Role::tags ()
Tags the role is tagged with
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\Role\RoleRoleTagController\index().
users()
BristolSU\ControlDB\Contracts\Models\Role::users ()
Users who occupy the role
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\Role\RoleUserController\index().
The documentation for this interface was generated from the following file:
src/Contracts/Models/Role.php