Bristol SU Control: BristolSU\ControlDB\Contracts\Models\Tags\RoleTag Interface Reference
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag Interface Reference
Public Member Functions
id ()
name ()
description ()
reference ()
categoryId ()
category ()
fullReference ()
roles ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
setTagCategoryId (int $categoryId)
addRole (Role $role)
removeRole (Role $role)
Detailed Description
Represents a Role Tag
Definition at line 15 of file RoleTag.php.
Member Function Documentation
addRole()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::addRole (Role $role)
Add a role to the tag
Parameters
Role $role
category()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::category ()
Tag Category
Returns
RoleTagCategory
categoryId()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::categoryId ()
ID of the tag category
Returns
int
Implemented in BristolSU\ControlDB\Models\Tags\RoleTag.
description()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::description ()
Description of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\RoleTag.
fullReference()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::fullReference ()
Full reference of the tag
This should be the tag category reference and the tag reference, separated with a period.
Returns
string
id()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::id ()
ID of the role tag
Returns
int
Implemented in BristolSU\ControlDB\Models\Tags\RoleTag.
Referenced by BristolSU\ControlDB\Repositories\Pivots\Tags\RoleRoleTag\addTagToRole(), BristolSU\ControlDB\Repositories\Pivots\Tags\RoleRoleTag\getRolesThroughTag(), BristolSU\ControlDB\Repositories\Pivots\Tags\RoleRoleTag\getTagsThroughRole(), and BristolSU\ControlDB\Repositories\Pivots\Tags\RoleRoleTag\removeTagFromRole().
name()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::name ()
Name of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\RoleTag.
reference()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::reference ()
Reference of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\RoleTag.
removeRole()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::removeRole (Role $role)
Remove a role from the tag
Parameters
Role $role
roles()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::roles ()
Roles who have this tag
Returns
Collection
setDescription()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::setDescription (string $description)
Set the description of the tag
Parameters
string $description
Implemented in BristolSU\ControlDB\Models\Tags\RoleTag.
setName()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::setName (string $name)
Set the name of the tag
Parameters
string $name
Implemented in BristolSU\ControlDB\Models\Tags\RoleTag.
setReference()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::setReference (string $reference)
Set the reference of the tag
Parameters
string $reference
Implemented in BristolSU\ControlDB\Models\Tags\RoleTag.
setTagCategoryId()
BristolSU\ControlDB\Contracts\Models\Tags\RoleTag::setTagCategoryId (int $categoryId)
Set the tag category ID
Parameters
int $categoryId
The documentation for this interface was generated from the following file:
src/Contracts/Models/Tags/RoleTag.php