Bristol SU Control: BristolSU\ControlDB\Contracts\Models\Group Interface Reference
BristolSU\ControlDB\Contracts\Models\Group Interface Reference
Public Member Functions
id ()
dataProviderId ()
setDataProviderId (int $dataProviderId)
data ()
members ()
roles ()
tags ()
addTag (GroupTag $groupTag)
removeTag (GroupTag $groupTag)
addUser (User $user)
removeUser (User $user)
Detailed Description
Represents a group
Definition at line 13 of file Group.php.
Member Function Documentation
addTag()
BristolSU\ControlDB\Contracts\Models\Group::addTag (GroupTag $groupTag)
Add a group tag to the group
Parameters
GroupTag $groupTag
Referenced by BristolSU\ControlDB\Http\Controllers\Group\GroupGroupTagController\update().
addUser()
BristolSU\ControlDB\Contracts\Models\Group::addUser (User $user)
Add a user to the group
Parameters
User $user
Referenced by BristolSU\ControlDB\Http\Controllers\Group\GroupUserController\update().
data()
BristolSU\ControlDB\Contracts\Models\Group::data ()
Get the DataGroup attached to the group
Returns
DataGroup
Referenced by BristolSU\ControlDB\Models\Group\getDataAttribute(), and BristolSU\ControlDB\Http\Controllers\Group\GroupController\update().
dataProviderId()
BristolSU\ControlDB\Contracts\Models\Group::dataProviderId ()
Get the ID of the data provider
Returns
int
Implemented in BristolSU\ControlDB\Models\Group.
id()
BristolSU\ControlDB\Contracts\Models\Group::id ()
ID of the group
Returns
int
Implemented in BristolSU\ControlDB\Models\Group.
Referenced by BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag\addTagToGroup(), BristolSU\ControlDB\Repositories\Pivots\UserGroup\addUserToGroup(), BristolSU\ControlDB\Http\Controllers\Group\GroupController\destroy(), BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag\getGroupsThroughTag(), BristolSU\ControlDB\Repositories\Pivots\UserGroup\getGroupsThroughUser(), BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag\getTagsThroughGroup(), BristolSU\ControlDB\Repositories\Pivots\UserGroup\getUsersThroughGroup(), BristolSU\ControlDB\Repositories\Pivots\Tags\GroupGroupTag\removeTagFromGroup(), and BristolSU\ControlDB\Repositories\Pivots\UserGroup\removeUserFromGroup().
members()
BristolSU\ControlDB\Contracts\Models\Group::members ()
Members of the group
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\Group\GroupUserController\index().
removeTag()
BristolSU\ControlDB\Contracts\Models\Group::removeTag (GroupTag $groupTag)
Remove a group tag from the group
Parameters
GroupTag $groupTag
Referenced by BristolSU\ControlDB\Http\Controllers\Group\GroupGroupTagController\destroy().
removeUser()
BristolSU\ControlDB\Contracts\Models\Group::removeUser (User $user)
Remove a user from the group
Parameters
User $user
Referenced by BristolSU\ControlDB\Http\Controllers\Group\GroupUserController\destroy().
roles()
BristolSU\ControlDB\Contracts\Models\Group::roles ()
Roles belonging to the group
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\Group\GroupRoleController\index().
setDataProviderId()
BristolSU\ControlDB\Contracts\Models\Group::setDataProviderId (int $dataProviderId)
Set the data provider ID
Parameters
int $dataProviderId
Implemented in BristolSU\ControlDB\Models\Group.
tags()
BristolSU\ControlDB\Contracts\Models\Group::tags ()
Tags the group is tagged with
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\Group\GroupGroupTagController\index().
The documentation for this interface was generated from the following file:
src/Contracts/Models/Group.php