Bristol SU Control: BristolSU\ControlDB\Contracts\Models\Tags\UserTag Interface Reference
BristolSU\ControlDB\Contracts\Models\Tags\UserTag Interface Reference
Public Member Functions
id ()
name ()
description ()
reference ()
categoryId ()
category ()
fullReference ()
users ()
setName (string $name)
setDescription (string $description)
setReference (string $reference)
setTagCategoryId (int $categoryId)
addUser (User $user)
removeUser (User $user)
Detailed Description
Represents a User Tag
Definition at line 15 of file UserTag.php.
Member Function Documentation
addUser()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::addUser (User $user)
Add a user to the tag
Parameters
User $user
Referenced by BristolSU\ControlDB\Http\Controllers\UserTag\UserTagUserController\update().
category()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::category ()
Tag Category
Returns
UserTagCategory
Referenced by BristolSU\ControlDB\Http\Controllers\UserTag\UserTagUserTagCategoryController\index().
categoryId()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::categoryId ()
ID of the tag category
Returns
int
Implemented in BristolSU\ControlDB\Models\Tags\UserTag.
description()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::description ()
Description of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\UserTag.
fullReference()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::fullReference ()
Full reference of the tag
This should be the tag category reference and the tag reference, separated with a period.
Returns
string
Referenced by BristolSU\ControlDB\Models\Tags\UserTag\getFullReferenceAttribute().
id()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::id ()
ID of the user tag
Returns
int
Implemented in BristolSU\ControlDB\Models\Tags\UserTag.
Referenced by BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag\addTagToUser(), BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController\destroy(), BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag\getTagsThroughUser(), BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag\getUsersThroughTag(), and BristolSU\ControlDB\Repositories\Pivots\Tags\UserUserTag\removeTagFromUser().
name()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::name ()
Name of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\UserTag.
reference()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::reference ()
Reference of the tag
Returns
string
Implemented in BristolSU\ControlDB\Models\Tags\UserTag.
removeUser()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::removeUser (User $user)
Remove a user from the tag
Parameters
User $user
Referenced by BristolSU\ControlDB\Http\Controllers\UserTag\UserTagUserController\destroy().
setDescription()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::setDescription (string $description)
Set the description of the tag
Parameters
string $description
Implemented in BristolSU\ControlDB\Models\Tags\UserTag.
Referenced by BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController\update().
setName()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::setName (string $name)
Set the name of the tag
Parameters
string $name
Implemented in BristolSU\ControlDB\Models\Tags\UserTag.
Referenced by BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController\update().
setReference()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::setReference (string $reference)
Set the reference of the tag
Parameters
string $reference
Implemented in BristolSU\ControlDB\Models\Tags\UserTag.
Referenced by BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController\update().
setTagCategoryId()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::setTagCategoryId (int $categoryId)
Set the tag category ID
Parameters
int $categoryId
Referenced by BristolSU\ControlDB\Http\Controllers\UserTag\UserTagController\update().
users()
BristolSU\ControlDB\Contracts\Models\Tags\UserTag::users ()
Users who have this tag
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\UserTag\UserTagUserController\index().
The documentation for this interface was generated from the following file:
src/Contracts/Models/Tags/UserTag.php