Bristol SU Control: BristolSU\ControlDB\Contracts\Models\Position Interface Reference
BristolSU\ControlDB\Contracts\Models\Position Interface Reference
Public Member Functions
id ()
dataProviderId ()
setDataProviderId (int $dataProviderId)
data ()
roles ()
tags ()
addTag (PositionTag $roleTag)
removeTag (PositionTag $roleTag)
Detailed Description
Represents a position
Definition at line 15 of file Position.php.
Member Function Documentation
addTag()
BristolSU\ControlDB\Contracts\Models\Position::addTag (PositionTag $roleTag)
Add a tag to the position
Parameters
PositionTag $roleTag
Referenced by BristolSU\ControlDB\Http\Controllers\Position\PositionPositionTagController\update().
data()
BristolSU\ControlDB\Contracts\Models\Position::data ()
The data attributes of the position
Returns
DataPosition
Referenced by BristolSU\ControlDB\Models\Position\getDataAttribute(), and BristolSU\ControlDB\Http\Controllers\Position\PositionController\update().
dataProviderId()
BristolSU\ControlDB\Contracts\Models\Position::dataProviderId ()
The ID of the data provider
Returns
int
Implemented in BristolSU\ControlDB\Models\Position.
id()
BristolSU\ControlDB\Contracts\Models\Position::id ()
ID of the position
Returns
int
Implemented in BristolSU\ControlDB\Models\Position.
Referenced by BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag\addTagToPosition(), BristolSU\ControlDB\Http\Controllers\Position\PositionController\destroy(), BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag\getPositionsThroughTag(), BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag\getTagsThroughPosition(), and BristolSU\ControlDB\Repositories\Pivots\Tags\PositionPositionTag\removeTagFromPosition().
removeTag()
BristolSU\ControlDB\Contracts\Models\Position::removeTag (PositionTag $roleTag)
Remove a tag from the position
Parameters
PositionTag $roleTag
Referenced by BristolSU\ControlDB\Http\Controllers\Position\PositionPositionTagController\destroy().
roles()
BristolSU\ControlDB\Contracts\Models\Position::roles ()
Roles with this position
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\Position\PositionRoleController\index().
setDataProviderId()
BristolSU\ControlDB\Contracts\Models\Position::setDataProviderId (int $dataProviderId)
Set the data provider ID
Parameters
int $dataProviderId
Implemented in BristolSU\ControlDB\Models\Position.
tags()
BristolSU\ControlDB\Contracts\Models\Position::tags ()
Tags the position is tagged with
Returns
Collection
Referenced by BristolSU\ControlDB\Http\Controllers\Position\PositionPositionTagController\index().
The documentation for this interface was generated from the following file:
src/Contracts/Models/Position.php